### ISSUE TITLE
Can not get the latest version of package in npm registry

### ISSUE THREAD

**Issue by RichieChoo** [verdaccio/verdaccio#1547] opened 2019-11-04 02:50 UTC
**Describe the bug**
Can not get the latest version of package in npm registry. 
I find that the package is update in one hour.

**Expected behavior**
 get the latest version of package and npm install success.

**Environment information**
node:v8.12.0
npm :6.4.1

**Comment by DanielRuf** [comment] 2019-11-04 06:10
Hi @RichieChoo,

Please clarify what you mean and let us know how we can reproduce this.

**Comment by RichieChoo** [comment] 2019-11-05 01:29
I have tried to install dependencies for a project . There are some packages in my verdaccio and some packages in npm registry ，and install throw an error that a npm packages 500 error . I find the package in npm registry , and it was updated for a new version in a hour . After a while , I install success

**Comment by DanielRuf** [comment] 2019-11-05 04:34
This seems like a caching issue.

**Comment by juanpicado** [comment] 2019-11-08 06:45
Agree with @DanielRuf , closing this.  Thanks @RichieChoo feel free to keep posting, but this is not a bug in our side.

**Closed by juanpicado** 2019-11-08 06:45 UTC
Labels: issue: invalid
