### ISSUE TITLE
Verdaccio gets really slow after long uptime

### ISSUE THREAD

**Issue by rbarato** [verdaccio/verdaccio#855] opened 2018-07-27 11:44 UTC
We use verdaccio as local storage for our components that cannot be published into npm and after an average uptime of 3 days it gets really slow, making even the server access via ssh slow. It's running on a ubuntu VM with 4 cpus and 8gb of ram, under forever service.

Could this be an verdaccio issue?

**Comment by juanpicado** [comment] 2018-07-27 11:46
@rbarato `verdaccio` is really light and does not run any job in the background. I ignore how much usage you are giving it but I'd recommend inspect your ubuntu processes and see what's causing such issue.

**Comment by ayusharma** [comment] 2018-07-27 11:58
Please share some logs and reasons which you find. We'll be happy to help you :)

**Comment by rbarato** [comment] 2018-07-27 16:49
Hi guys, currently verdaccio is using 1gb of ram and its % of cpu varies depends on how many users are downloading packages, which is ok. What I noticed was a huge improvement by switching from forever to nohup. I've changed right after opening the issue and it seems to be fixed. I'll keep on monitoring and I guess this issue can be closed as it really doesn't look a verdaccio issue.

Thanks and regards.

**Comment by juanpicado** [comment] 2018-07-27 17:21
@rbarato users will love your Feedback here https://verdaccio.org/docs/en/server-configuration#keeping-verdaccio-running-forever :-) feel free to PR when you have your final outcome. Thanks for the feedback.

**Comment by rbarato** [comment] 2018-08-03 18:59
After 70+ hours of uptime using nohup, verdaccio has gone wild with the cpu again, look at the top log I just printed:

![screen shot 2018-08-03 at 15 46 17](https://user-images.githubusercontent.com/1949592/43660302-f54fef4c-9734-11e8-94d6-0e50fe9c1902.png)

The /storage currently has 2.7G of stored packages. 

Any clues?

**Comment by dlouzan** [comment] 2018-08-05 00:15
I personally haven't experienced it, but as @ayusharma mentioned, a couple of things that might help:
- Check the health of your os, maybe you're run out of some resource (inodes?)
- Logs would be really helpful, and you can increase the log level. Additionally, does verdaccio keep working normally after the fact? (not taking into account the high cpu load)
- Lastly, you might run some node profiler and send the profile result. That should help with identifying where the process is spending the cpu time

**Comment by rbarato** [comment] 2018-08-06 12:02
Thanks @dlouzan for the reply. About inods, it's ok, the VM has plenty of disk and other resources available. After verdaccio gets slow,  it doesn't return to normal, I have to kill the process and start again. 

I've raised log levels to fatal,error, warn and let's see if it helps me figuring it out.

Will keep you posted.

Thanks

**Comment by dlouzan** [comment] 2018-08-06 14:04
@rbarato Cool, ideally and if it's ok for your use case, raise it even more to debug or trace (isn't warn the default?); that should help identifying where the issue is happening, if this is verdaccio's fault.

**Comment by farfromrefug** [comment] 2018-08-20 13:47
Same thing happening to me. I run verdaccio on a docker. When running heavy requests (like npm I from scratch on a very heavy project), verdaccio become too slow. I have to restart the docker.
My log level is to fatal.

However the CPU/RAM does not show anything wrong.
Will try to run Verdaccio with logs to see If I can catch something wrong.

**Comment by farfromrefug** [comment] 2018-09-03 07:28
@SheetJSDev would have to run some tests but might take some times as we run Verdaccio on a remote google cloud vm.  Will try and do so

**Comment by rbarato** [comment] 2018-09-28 13:57
Sorry the delay on this, @SheetJSDev I didn't try to use tmux, will do. It's been almost a month and it only crashed again once in this time. However when it crashed I didn't restart it, I just let it happen and magically after around 15 minutes it came back to life by itself, lowering cpu usage and becoming available again - the process never stoped. So based on this I'm inclined to assume it's some other process running in the VM (maybe some backup) that's causing this issue, the only strange thing is that when that happens the whole machine becomes slow and by killing verdaccio process it fixes the performance. I've checked cron and there's nothing there.

**Comment by juanpicado** [comment] 2019-02-26 06:13
Hi guys, I've been running a registry for all builds in verdaccio for PR and Docker images, even the lock files point to our registry. In 3 months monitoring the registry, I haven't seen any suspicious spike at the CPU or big memory consumption. Our environment is a tiny 5$ droplet at DigitalOcean. So, I'll close this, if someone experiences any issue, feel free to post details.

**Closed by juanpicado** 2019-02-26 06:13 UTC
Labels: discuss, question
