### ISSUE TITLE
url_prefix changed behaviour with 4.2.2

### ISSUE THREAD

**Issue by lukebelliott** [verdaccio/verdaccio#1523] opened 2019-10-16 14:37 UTC
I had Verdaccio 4.2.1 running behind an apache proxy working well and just tried upgrading to latest and it's no longer working. Tracked the change in behaviour to 4.2.2.

I have the prefix configured in verdaccio's config:

```url_prefix: /npm/```

Apache proxy config:
```
<Location /npm/>
    ProxyPass https://127.0.0.1:4873/ nocanon
    ProxyPassReverse https://127.0.0.1:4873/
    ProxyPreserveHost On
</Location>
```

With 4.2.1, this is working perfectly. Here's a diff of the initial GET response from 4.2.1 and 4.2.2 out of Verdaccio itself (not apache):
```
--- good.4.2.1.txt      2019-10-16 15:20:18.931210851 +0100
+++ bad-4.2.2.txt       2019-10-16 15:19:44.480775891 +0100
@@ -15,12 +15,12 @@
         window.VERDACCIO_SCOPE = '';
         window.VERDACCIO_LOGO = '';
         window.VERDACCIO_PRIMARY_COLOR = '';
-        window.VERDACCIO_VERSION = '4.2.1';
+        window.VERDACCIO_VERSION = '4.2.2';
     </script>
-<link rel="shortcut icon" href="http://ukserver.activfinancial.com/npm/-/static/favicon.ico"><link href="http://ukserver.activfinancial.com/npm/-/static/0.style.026be7a5bc0c57143eb2.css" rel="stylesheet"><link href="http://ukserver.activfinancial.com/npm/-/static/2.style.92647ec0a7beb8b2898d.css" rel="stylesheet"></head>
+<link rel="shortcut icon" href="/-/static/favicon.ico"><link href="/-/static/0.style.2ea8a5d1276179958242.css" rel="stylesheet"><link href="/-/static/2.style.92647ec0a7beb8b2898d.css" rel="stylesheet"></head>
 
 <body class="body">
     <div id="root"></div>
-<script type="text/javascript" src="http://ukserver.activfinancial.com/npm/-/static/manifest.36047715e70284b71dcd.js"></script><script type="text/javascript" src="http://ukserver.activfinancial.com/npm/-/static/vendors.36047715e70284b71dcd.js"></script><script type="text/javascript" src="http://ukserver.activfinancial.com/npm/-/static/main.36047715e70284b71dcd.js"></script></body>
+<script type="text/javascript" src="/-/static/manifest.64e04f9f5e62cc8e0fd4.js"></script><script type="text/javascript" src="/-/static/vendors.64e04f9f5e62cc8e0fd4.js"></script><script type="text/javascript" src="/-/static/main.64e04f9f5e62cc8e0fd4.js"></script></body>
 
 </html>
```

As you can see, scripted sources are relative in 4.2.2. I can't see anything in the changelog that would indicate a config change is required or what else might have caused this (maybe it should never have worked like I have it configured?).

A quick diff of the 4.2.1 and 4.2.2 tags shows few changes to verdaccio so I guess it's one of the dependencies, but I've no idea where ...

There are a few other issues referencing url_prefix, but they seem to predate 4.2.2 so presumably aren't related. Apologies if this is just noise, but I am a bit stumped...

Regards

**Comment by juanpicado** [comment] 2019-10-17 04:53
@lukebelliott I was testing https://github.com/verdaccio/docker-examples/tree/master/reverse_proxy/nginx with all v4 versions, do difference at all. Unfortunately I have no apache example for relative paths, only a normal setup from root. If you are able to reproduce it with any example in that repo let me know.

I `4.2.2` we fixed https://github.com/verdaccio/ui/issues/108 and still works in our examples, I'd double check https://verdaccio.org/docs/en/reverse-proxy see whether you comply with all required fields.

**Comment by lukebelliott** [comment] 2019-10-18 11:07
I tried to get the reverse_proxy/nginx/relative_path example working, but it fails with ```fatal--- cannot open config file /verdaccio/conf/config.yaml``` so I guess I'm missing something, just not sure what. Sadly I'm not a docker person but If anyone could give me a pointer I'd be grateful and happy to try again.

Instead I tried a nginx setup on my server using:

```
        location ~ ^/npm/(.*)$ {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-NginX-Proxy true;
            proxy_pass http://127.0.0.1:4873/$1;
            proxy_redirect off;

#           proxy_pass http://127.0.0.1:4873/$1;
#           proxy_set_header Host            $host:$server_port;
#           proxy_set_header X-Forwarded-For $remote_addr;
#           proxy_set_header X-Forwarded-Proto $scheme;
        }

And it fails the same way as apache for me (with either version). That initial GET from verdaccio has, for example:

```
<link rel="shortcut icon" href="/-/static/favicon.ico"><link href="/-/static/0.style.2ea8a5d1276179958242.css" rel="stylesheet"><link href="/-/static/2.style.92647ec0a7beb8b2898d.css" rel="stylesheet"></head>
```

which unless the proxy is going to start rewriting bodies surely can't work?

Looking at the nginx config in the repo, isn't it serving from both / and /verdaccio? So the  non-prefixed hrefs in the initial GET response will still work?

If I add in / to my nginx setup:

```
        location / {
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Host $host:$server_port;
              proxy_set_header X-NginX-Proxy true;
              proxy_pass http://127.0.0.1:4873;
              proxy_redirect off;
        }
```

to look like the example in the repo, then it does indeed work, but everything is served off /.

Like I say, happy to try with the docker example if someone could let me know what I'm missing!

Thanks

**Comment by juanpicado** [comment] 2019-10-19 07:06
I'm not super expert in Apache unfortunately, but please provide a repo with examples of your configuration, so anyone can try to reproduce it. Let's see wether someone with Apache skills can help here.

**Comment by lukebelliott** [comment] 2019-10-19 13:47
Sorry if it wasn't clear from my previous message, I don't think it's anything to do with apache as I get the exact same behaviour with nginx on my server.

Also, since then, I managed to get docker-examples/reverse_proxy/nginx/relative_path running, and that shows the issue too if the ```location /``` section is removed.

With the default config from the example (```location /``` still there), then you can see a bunch of requests don't have the url_prefix. Here's a quick summary of the URLs (as seen from the browser in this case):

* GET http://lukee-home/verdaccio/
* GET http://lukee-home/-/static/0.style.ce77317cdb424d2f38d8.css
* GET http://lukee-home/-/static/manifest.ba207bfcf72b6ad80f79.js
* GET http://lukee-home/-/static/vendors.ba207bfcf72b6ad80f79.js
* GET http://lukee-home/-/static/main.ba207bfcf72b6ad80f79.js
* GET http://lukee-home/verdaccio/-/verdaccio/packages
* GET http://lukee-home/verdaccio/-/static/93df1ce974e744e7d98f5d842da74ba0.svg

... and so on ...

Regards

**Comment by chrisbertrandsagecom** [comment] 2019-10-22 09:43
I am experiencing the exact same problem.  Only the favicon is correctly retrieved from the url_prefix. Everything else is served from root, which is not where the files reside. 

![image](https://user-images.githubusercontent.com/38248088/67274652-ceab3f80-f4b8-11e9-92db-d480eb1dd076.png)

**Comment by krrishh-org** [comment] 2019-11-18 12:19
I am also experiencing the same issue here. We have an internal reverse proxy similar to nginx. The static files are not getting resolved as they were in 4.2.1

**Comment by chrisbertrandsagecom** [comment] 2019-11-18 14:14
A workaround for those that are using Nginx, and have this problem.

Amend your config to rewrite those paths back in, there were some additional changes that were needed.
```
proxy_set_header Accept-Encoding "";
proxy_set_header X-NginX-Proxy 
sub_filter '/-/static/' '/npm/-/static/';
sub_filter_types text/html text/css;
sub_filter_once off;
```

**Comment by krrishh-org** [comment] 2019-11-18 14:24
Ok. For now I have rebuilt the ui  with [this change](https://github.com/verdaccio/ui/commit/5a9bd6001a2de58eabd62942c1486be6839a9930#diff-2a11159a0f72e5ac0dd32dadc5f8398aL11) reverted and replaced it in the verdaccio installation. It is working fine for now. Need a permanent fix for this.

**Comment by a666** [comment] 2019-11-21 20:01
We also just updated, and fell on this issue. We did the same than @chrisbertrandsagecom.

Also this issue also requires the nginx tag.

**Comment by 9ae8sdf76** [comment] 2019-12-10 19:13
I'm having the same problem. Brand new install today. Looking at the webpack.config.js in the ui repo, it looks like it might be because of the `publicPath: '/-/static',`, which looks to be related to removing the `ToReplaceByVerdaccio` as denoted by [this comment](https://github.com/verdaccio/verdaccio/issues/1523#issuecomment-543000892).

This would mean it's not a web server configuration problem. It's a code problem. I'm going to take others' advice and downgrade to 4.2.1 until this gets fixed. ✌️

**Comment by nsainaney** [comment] 2020-04-15 04:06
I can confirm this issue on Kubernetes as well (using Istio for reverse proxy).

**Comment by juanpicado** [comment] 2020-04-15 04:41
> I can confirm this issue on Kubernetes as well (using Istio for reverse proxy).

I appreciate the feedback, but, I think each of you is having this issue, please, share your configuration, context, etc, otherwise would be hard to narrow down the issue. If it is the same as above, confirm it 🙏  also would be helpful for triage this. As much context, the better.

**Comment by taffarel-gaivota** [comment] 2020-04-27 15:35
@nsainaney you can fix this issue using Istio as reverse proxy forcing Istio add the **X-Forwarded-Proto** and **X-Forwarded-Port**

Example

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: npm
spec:
  hosts:
    - 'npm.my-server.com'
  gateways:
    - istio-gateway
  http:
    - route:
      - destination:
          host: verdaccio
          port:
            number: 4873
      **headers:
        request:
          set:
            X-Forwarded-Proto: "https"
            X-Forwarded-Port: "443"**
```

**Comment by nsainaney** [comment] 2020-04-28 03:40
Thanks @taffarel-gaivota. We opted to route based on verdaccio being its own host (verdaccio.xxx.example.com) and it's working fine now but we'll test the above and circle back with a config that can reliably reproduce the issue.

**Comment by taffarel-gaivota** [comment] 2020-04-29 18:29
For those who are using Apache server you can do some as this


```
<Location /npm/>
        ProxyPreserveHost on
        ProxyPass http://127.0.0.1:4873/ nocanon
        ProxyPassReverse http://127.0.0.1:4873/
        RequestHeader   setIfEmpty      X-Forwarded-Proto    "https"
        RequestHeader   setIfEmpty      X-Forwarded-Port    "443"
    </Location>
```

and for Nginx you can do something like this: 
```
location /some/path/ {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto "https"
    proxy_set header X-Forwarded-Port 443
    proxy_pass http://localhost:8000;
}
```

**Comment by 494310051** [comment] 2020-06-03 01:52
confirm this issue on  4.6.2 
html temple should add <base href="./">

**Comment by harty911** [comment] 2020-06-15 15:52
> With the default config from the example (`location /` still there), then you can see a bunch of requests don't have the url_prefix. Here's a quick summary of the URLs (as seen from the browser in this case):
> 
> * GET http://lukee-home/verdaccio/
> * GET http://lukee-home/-/static/0.style.ce77317cdb424d2f38d8.css
> * GET http://lukee-home/-/static/manifest.ba207bfcf72b6ad80f79.js
> * GET http://lukee-home/-/static/vendors.ba207bfcf72b6ad80f79.js
> * GET http://lukee-home/-/static/main.ba207bfcf72b6ad80f79.js
> * GET http://lukee-home/verdaccio/-/verdaccio/packages
> * GET http://lukee-home/verdaccio/-/static/93df1ce974e744e7d98f5d842da74ba0.svg
> 
> ... and so on ...

**I can confirm the issue when loading the index.html page on my side too.**
Looking at the code, this is a problem comming from `index.hml` template in `@verdaccio/ui-theme` package.

`index.hml` page template is loaded and modified according to this replace statement (were base is the root public url including url_prefix):

```js
template.replace(/ToReplaceByVerdaccio/g, base)
```

But in  ìndex.html` template there is:
```html
...
<link rel="icon" type="image/png" href="ToReplaceByVerdaccio/-/static/favicon.ico" />
...
<link rel="shortcut icon" href="/-/static/favicon.ico">
<link href="/-/static/0.style.b3d2b69b057068c678ca.css" rel="stylesheet">
...
<script type="text/javascript" src="/-/static/manifest.23e9430e154f72ad4c9c.js"></script>
<script type="text/javascript" src="/-/static/vendors.23e9430e154f72ad4c9c.js"></script>
<script type="text/javascript" src="/-/static/main.23e9430e154f72ad4c9c.js"></script>
...
```
=> not all URL are prefixed with base

> Replacing all `"/-/static/..."` by `ToReplaceByVerdaccio/-/static/..."` in template worked for me !**
>
> Is it possible to fix template ? (I don't know where is this repo)

**Comment by jsiedentop** [comment] 2020-06-16 12:14
@harty911 explained the problem very acurate. The reason, why @juanpicado can't reproduce the problem is, that the example (https://github.com/verdaccio/docker-examples/tree/master/reverse_proxy/nginx) is serving an instance on http://localhost/ and http://localhost/verdaccio. So the broken links from the second instance are served from the first instance. As @harty911 already mentioned, a deeper look into the browser tools disclose the bug. 

I think it would be a good idea to also fix the example to something like that:
- http://localhost/  (nothing or an index page)
- http://localhost/v3 (instance one)
- http://localhost/v4 (instance two)

Thanks for all your efford 👍

**Comment by bsh-ableton** [comment] 2020-08-29 16:24
It looks like this was introduced when the prefix was removed in https://github.com/verdaccio/ui/pull/122. 

So, to link in the relevant GitHub issues:
 - _having_ the prefix was problematic in the CSS files (https://github.com/verdaccio/ui/issues/108)
 - _not having_ the prefix prevents the url_prefix from being applied (https://github.com/verdaccio/verdaccio/issues/1523)
 - the docker relative path example conceals the issue by serving v3 and v4 at the same time (https://github.com/verdaccio/docker-examples/issues/29)

**Comment by SamuelToh** [comment] 2020-09-04 04:14
Can confirm this is a major road block for those wanting to host Verdaccio on a sub path other than the / root.
:sob:

**Comment by tekhedd** [comment] 2020-09-28 17:09
For workaround-seekers: I can confirm that the X-Forwarded-Proto/X-Forwarded-Port does *not* fix the UI with latest (4.8.1), and does not appear to affect the command-line functionality root either.

(In other words, if you're trying the workaround and it's not working, it's not just you.)

**Comment by maccuaa** [comment] 2021-01-08 01:54
It's ugly but this workaround worked for me - https://github.com/verdaccio/ui/issues/263#issuecomment-748596488

Caddy config:

```
handle_path /npm* {
        reverse_proxy localhost:4873
}

handle /-/static/* {
        reverse_proxy localhost:4873
}
```

**Comment by juanpicado** [comment] 2021-03-11 11:00
I'll take of this #2122 please follow up there.

**Comment by juanpicado** [comment] 2021-03-24 18:37
You can start to test the branch pulling this 

```
docker pull verdaccio/verdaccio:proxy_fix_1523
```
I will update automatically when new commits are pushed.  No npm version ready yet.

**Closed** 2021-03-29 10:32 UTC
Labels: help wanted, topic: apache, topic: proxy

**Comment by juanpicado** [comment] 2021-03-30 20:25
FYI, fix for this is on verdaccio 5.
