### ISSUE TITLE
Access to only allowed packagesfrom npmjs (+ dependencies)

### ISSUE THREAD

**Issue by Fatal1stZ** [verdaccio/verdaccio#585] opened 2018-02-21 08:44 UTC
#### My reason:

Greetings! Is there any way to allow the only packages via verdaccio?

I need to provide only some packages for team development (e.g. react, redux etc) due to security reasons. The developers are isolated from Intenet, so we need a caching proxy for npmjs with only allowed packages.

We use nexus to get to npmjs. So the uplink is npm-nexus.
The rule for packages is:
packages:

```
  '**':
    access: admin
    publish: admin
    proxy: npm-nexus
```

It means that only admin can download packages. For example, a team needs new package to work with. Admin downloads that package and it caches.

And then we add it packages section:
packages:

```
  'react':
    access: $all
  '**':
    access: admin
    publish: admin
    proxy: npm-nexus
```

But, the problem is when non-authorized users try to npm install react they get a message:
unregistered users are not allowed to access package fbjs : fbjs
That means that dependencies are not allowed. We need to add each dependency into packages package, what is ovewhelming.

The other way is to cache all needed packages under admin user and then allow all packages public accsess, but remove proxy. But this is unnecessary modyifing config file every time we need to add new package to cache.

Any solution for this? May be there is another npm package for this or some kind of plugin?

**Comment by juanpicado** [comment] 2018-03-15 20:42
> I need to provide only some packages for team development (e.g. react, redux etc) due to security reasons. 

Well,  I understand your issue, but, I do not have any possible solution in mind. This clearly sounds like customized workflow. 

> But, the problem is when non-authorized users try to npm install react they get a message:
unregistered users are not allowed to access package fbjs : fbjs

Verdaccio is not aware of dependencies, `npm`/`yarn` handle that part. We do not collect relationships between packages. Just fetch, storage and handle restrictions for single packages.

> The other way is to cache all needed packages under admin user and then allow all packages public access, but remove the proxy. But this is unnecessary modifying config file every time we need to add new package to cache.

Yeah, it's annoying. But that's the reason why we allow plugins, for such edge case scenarios. 

I'll close this ticket since is not a bug or feature, it's just a question, I'll label it and let's see whether someone else can help you.

**Closed by juanpicado** 2018-03-15 20:42 UTC
