### ISSUE TITLE
Latest behind available versions

### ISSUE THREAD

**Issue by jonathancreamer-eb** [verdaccio/verdaccio#1591] opened 2019-11-22 15:04 UTC
**Describe the bug**
Has anyone ever seen or might know why the dist-tag or latest is behind a patch version of what's available?

![](https://d.pr/i/f3PKYJ+)

![](https://d.pr/i/wVrei8+)

We use a tool called `changesets` to determine when to publish a package, and since the version is behind, our package.json is set at 3.0.7, but `npm dist-tag` is returning 3.0.6 even though 3.0.7 is in Verdaccio, just not set as latest.

```Dockerfile
FROM verdaccio/verdaccio:4.0.1
ENV PORT=80
USER root
RUN npm install && \
  test -d node_modules
RUN npm install \
  verdaccio-htpasswd \
  verdaccio-s3-storage
COPY logo-white.png .
COPY config.yaml /verdaccio/conf/config.yaml
COPY htpasswd.txt /verdaccio/conf/htpasswd
```

We're using Kubernetes with 3 replicas.

**Comment by juanpicado** [comment] 2019-11-23 11:08
As we discussed in the chat docker channel, you will investigate more . I am just replying in case someone wants to give more info.

**Comment by jonathancreamer-eb** [comment] 2019-12-04 22:26
Yeah man, I still never got to the bottom of it. I had a theory that it was having multiple replicas of verdaccio in kubernetes and some kind of race condition between them, but never was able to confirm that. We're now having memory issues with it too which we were talking about in there, so we went down to one replica and back up to 3 to address memory issues, so if we start seeing the dist-tag issue again, we'll know it was from the extra replicas.

**Comment by DanielRuf** [comment] 2019-12-05 07:30
Well, someone has created the tag `latest`. Also npmjs has some caches. Afaik you have to create / update the `latest` tag manually.

**Comment by juanpicado** [comment] 2020-04-10 15:19
I'm closing this, too old, please if the error persist don't hesitate to comment and provide more information 👍

**Closed by juanpicado** 2020-04-10 15:19 UTC
Labels: issue: waiting-user-feedback

**Comment by jonathancreamer-eb** [comment] 2020-04-10 15:20
Thanks, no problem.

**Comment by aphix** [comment] 2020-04-13 17:33
Just hit this issue today; not quite sure what changed it, but I can see in the Verdaccio logs that prior publishes (~1 week ago) were followed with a PUT, whereas this one was not. 

I'll try manually updating the latest tag now.

**Comment by juanpicado** [comment] 2020-04-14 10:21
@aphix if you manage to describe a list of steps to follow to reproduce would be great. If I manage to reproduce then I can reopen this ticket.

**Comment by aphix** [comment] 2020-04-16 02:02
@juanpicado Will do; haven't needed to publish since but I'll make sure to record versions & steps next time I do in the off-chance it fails.

Unfortunately that publish was automated via a CI running in the office and everyone is working from home due to COVID so I have even less ability to inspect than normal. Thanks.

FWIW, manually updating the tag worked fine (via `npm dist-tag`) as a workaround.

**Comment by jonathancreamer-eb** [comment] 2020-04-16 14:02
That's ultimately what we did to fix as well @aphix. 🤷‍♂️
