### ISSUE TITLE
Stop Verdaccio using registry.npmjs.com (read-only mode)

### ISSUE THREAD

**Issue by GGGav** [verdaccio/verdaccio#1193] opened 2019-01-16 18:24 UTC
Is it possible to configure Verdaccio (in a docker container) to not call out to ‘registry.npmjs.com’ when something isn’t available locally?

We run a couple of Verdaccio instances in Docker containers and one of the is for release builds.  We want to be able to ‘freeze’ (no package changes) this instance during the ‘pre-release’ period and then unfreeze it (sometime) after release.

So far the only ways I have found of doing this are either to manipulate the local ‘/etc/hosts’ file so that ‘registry.npmjs.com’ doesn’t go any where useful or to rebuild the container with the storage mounted read only.  These both seem in-elegant.  Can I achieve what I want in config?

I have tried various things in config:
- commenting out the ‘uplinks’
- modifying the ‘url’ for the ‘npmjs’ uplink to point no where useful
- removing the ‘npmjs’ uplink; adding a ‘nowhere’ uplink with a useless ‘url’ and changing all my ‘packages’ to have “proxy: nowhere”

However with each of the above configurations Verdaccio still happily calls out to ‘registry.npmjs.com’.

Any suggestions?

**Comment by GGGav** [comment] 2019-01-16 18:46
Something like this would do.

[config-no-proxy.yaml.txt](https://github.com/verdaccio/verdaccio/files/2765620/config-no-proxy.yaml.txt)

But I can see lots of ways the config could do this (and I'm not precious about how we achieve the effect)

**Comment by juanpicado** [comment] 2019-01-16 18:48
Or remove the proxy field at all. That also works.

**Comment by GGGav** [comment] 2019-02-17 10:49
It would be shame for this to 'go stale' without a resolution.

**Comment by pierre42100** [comment] 2019-02-21 15:52
I have got the same problem.
Here is my configuration file:
`#
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://verdaccio.org/docs/en/docker#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage
# path to a directory with plugins to include
plugins: /verdaccio/plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: NONE


  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: NONE


# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
`

If I try to pull package when my Verdaccio instance is offline (I am using Docker), I get the following error even if the packages are available locally :
` fatal--- uncaught exception, please report this
Error: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)`

**Comment by GGGav** [comment] 2019-02-25 17:50
Juanpicado, you added 'need verification'.  Is there anything I can do for that?

**Comment by juanpicado** [comment] 2019-02-25 18:18
It is only to avoid the not close the ticket :)

**Comment by serdaryesilmurat** [comment] 2019-03-21 07:15
Any updates for this issue? Is there a working way to break the connection of verdaccio to npm registry entrirely.

**Comment by mkultra329** [comment] 2019-03-22 18:50
c

> Any updates for this issue? Is there a working way to break the connection of verdaccio to npm registry entrirely.

I just commented out the lines that reference npmjs in the config.yaml and it works fine for me. I also commented out the other two lines int he uplink section.

**Comment by serdaryesilmurat** [comment] 2019-03-25 06:04
I also commented out  "uplinks" field (with npmjs and url under it) and "proxy" field under "packages" in config.yaml. Did not work for me :(

**Comment by juanpicado** [comment] 2019-03-25 06:48
Ok guys, let me explain what is happening here by steps.
To understand this we need to back to 2013, when this project was sinopia back then.
https://github.com/verdaccio/verdaccio/commit/dfd0459c03f5f6e4155b74d9d5e482aa2d077d1c

Let's imagine I have `jquery` on my storage.
![Screen Shot 2019-03-25 at 7 34 35 AM](https://user-images.githubusercontent.com/558752/54899572-7daa7d00-4ed0-11e9-989b-429b354139dc.png)

and I have this on my project

```
 "dependencies": {
    "jquery": "^3.3.1"
  }
```
As you have noticed, I have the metadata already on my local storage. Then I'll remove `uplinks` and also comment out `proxy` on my package access section.

Let's open the metadata file and find for `3.3.1` and then the `dist` section. You will see

```
"dist": {
  "integrity": "sha512-Ubldcmxp5np52/ENotGxlLe6aGMvmF4R8S6tZjsP6Knsaxd/xp3Zrh50cG93lR6nPXyUFwzN3ZSOQI0wRJNdGg==",
  "shasum": "958ce29e81c9790f31be7792df5d4d95fc57fbca",
  "tarball": "https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz"
},
```
Let's put our focus on the `tarball` property for a while.

Then if you do `npm install` in your project, Verdacio will resolve properly `jquery` because we have it locally.
```
 http <-- 200, user: null(127.0.0.1), req: 'GET /jquery', bytes: 0/10262
```
Thus, the your local cache will also have a copy of the updated metadata.
Then the `npm` does a second call to request the desired tarball.

```
 info <-- 127.0.0.1 requested 'GET /jquery'
 http <-- 200, user: null(127.0.0.1), req: 'GET /jquery', bytes: 0/10262
 info <-- 127.0.0.1 requested 'GET /jquery/-/jquery-3.3.1.tgz'
 info --> making request: 'GET https://registry.verdaccio.org/jquery/-/jquery-3.3.1.tgz'
 http <-- 200, user: null(127.0.0.1), req: 'GET /jquery/-/jquery-3.3.1.tgz', bytes: 0/415379
```
and magically is being resolved. Why? Even if I have all my proxy commented out and no proxies at all.

The reason is, Verdaccio will create a `proxy` on hot even if you don't have anything defined in your configuration file. This has been like this since for ever. You can check the logic here

https://github.com/verdaccio/verdaccio/blob/master/src/lib/storage.js#L189

So, as long you have the metadata in your local storage Verdaccio will bypass your settings and fetch the tarball. 

If this is the right behavior, I'm not sure, it has been like this always and change it might be a breaking change, I'm not sure how many people is relying on this current behavior.

I will close this since is not a bug, let's call it, feature. Perhaps a new feature request is need it to disable this behavior.

**Closed by juanpicado** 2019-03-25 06:48 UTC
Labels: need verification, proxy, question

**Comment by serdaryesilmurat** [comment] 2019-03-25 08:13
Thank you for the detailed answer, very appreciated :)

The only thing that confuses me is that in an older version of verdaccio (3.0.2), that was not the case. Namely, it does not request npm registry (which causes the closing of verdaccio due to timeout), if local cache has the package. I can install packages from local cache (which has no internet connection), it does not trigger a npm registry call. Maybe it is due to the npm version, because for verdaccio 3.0.2, my npm version is 4.6.1. When I updated the verdaccio to 3.11.6, I also updated the npm to 6.4.1 and this problem occurred :(

**Comment by juanpicado** [comment] 2019-03-25 08:30
Yeah that might be, remember one thing, the one which does the request is the client, verdaccio is stateless and there is no connection between requests. Thus, what I do is try with different clients and see whether the behaviour is different.

**Comment by serdaryesilmurat** [comment] 2019-03-25 11:17
Reverted back to verdaccio 3.0.2 using the same storage folder and config file (with the latest npm version). It is working as expected now. I won't dig this any further. Thanks for the quick responses ;)

**Comment by juanpicado** [comment] 2019-03-25 11:37
Sure 👍 thanks for the feedback

**Comment by GGGav** [comment] 2019-03-25 19:08
I'm happy with the explanation and the closure.  I'll use my local environment to stop Verdaccio getting places I don't want it to go :)
