### ISSUE TITLE
HTTP 400 when using jwt

### ISSUE THREAD

**Issue by ViceIce** [verdaccio/verdaccio#1530] opened 2019-10-21 14:31 UTC
**Describe the bug**

If i enable jwt (which is enabled for web ui by default) i always get a 400 bad request reponse whenever i try to use the jwt auth token.
There is no log entry for the request.

**To Reproduce**
1. configure bitbucket-server as auth
2. push a package
3. login to webui
4. view browser console for 400 error

**Expected behavior**
jwt auth should just work with any auth module

**Screenshots**

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: [e.g. verdaccio:4.x]
 - Docker commands [e.g. docker pull ...] 
 - Docker Version [e.g. v18.05.0-ce-rc1] 18.09.9 / Rancher v1.6.28

https://github.com/VisualOn/docker-images/tree/master/docker/verdaccio

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```yaml
storage: /verdaccio/storage/data
plugins: /verdaccio/plugins

web:
  title: Verdaccio

auth:
  bitbucket-server:
    url: "http://server.bitbucket:7990"
    allow: "stash-users" # optional; default = ""

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  pkg:
    url: https://server.proget/npm/vo-npm/

packages:
  '@vo/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: pkg
    storage: vo
    
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
    storage: npmjs

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs    
    storage: npmjs

middlewares:
  audit:
    enabled: true

# log settings
logs:
  - { type: stdout, format: pretty, level: http }
  - { type: file, path: /verdaccio/storage/verdaccio.log, format: pretty-timestamped, level: debug }

experiments:
  # support for npm token command
  token: true
```

**Environment information**

  System:
    OS: Linux 5.0 Alpine Linux undefined
    CPU: (8) x64 AMD Opteron(tm) Processor 6380
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm

**Debugging output**

 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:

**Additional context**

**Comment by juanpicado** [comment] 2019-10-22 05:12
hi @ViceIce I don't see JWT enabled in your config file

**Comment by ViceIce** [comment] 2019-10-22 06:07
I've removed it to get `npm login` working. But the docu says it is automatically enabled for web-ui. I can login on web UI, but when it tries to fetch the packages I get the 400 error.

When I enable jwt for API I also get the 400 error with npm cli

**Comment by haritonstefan** [comment] 2019-11-20 13:40
@ViceIce I had a similar issue. It was because the user I was authorizing had access to too many groups, which in the end were encoded in the Jwt token, and made it too large.

**Comment by ViceIce** [comment] 2019-11-20 13:55
@haritonstefan I can see that the jwt token is very large. What can i do?

I'm using bitbucket as auth provider. It will send all groups, projects and repos as groups.
Projects and repos are multiplied by the 3 possible permission levels.
So for our small bitbucket instance i get ~3 groups, ~15 projects and ~25 repos, so overall ~115 verdaccio groups 😱 
What can we do here?

**Comment by juanpicado** [comment] 2019-11-20 14:07
@ViceIce @haritonstefan I read few months ago if you are using proxies to increase the header size in your (nginx or apache) by default is no able to handle such big header JWT size. Check other tickets, answer is over there.

**Comment by ViceIce** [comment] 2019-11-20 14:09
@juanpicado verdaccio is sending the 400, even without any proxy between.

**Comment by juanpicado** [comment] 2019-11-21 05:47
In such case, then would be great if you share some logging. As far I know Verdaccio does only return 400 in one case (login) and is not related with your issue.

**Comment by ViceIce** [comment] 2019-11-22 05:26
Ok, I'll try to create a reproducible test config

**Comment by ViceIce** [comment] 2019-11-28 17:42
https://nodejs.org/api/errors.html#errors_hpe_header_overflow

Looks like the default max header size is 8kb

see https://github.com/ViceIce/verdaccio-bug for reproducable

**Comment by ViceIce** [comment] 2019-11-28 18:48
using `roleTypes` reduces the number of groups now:

```yml
auth:
  bitbucket-server:
    url: "http://server.bitbucket:7990"
    allow: "stash-users"
    roleTypes: ['groups']
```

**Comment by DanielRuf** [comment] 2019-12-28 18:00
> nodejs.org/api/errors.html#errors_hpe_header_overflow

How is this exactly related to the 400 error which does not show this error ID / name?

We use express so this might be a problem with exress and the underlying network modules.

See https://github.com/expressjs/express/issues/4131#issuecomment-565655526 and https://github.com/expressjs/express/issues/3040

**Comment by DanielRuf** [comment] 2019-12-28 18:01
> nodejs.org/api/errors.html#errors_hpe_header_overflow

How is this exactly related to the 400 error which does not show this error ID / name?

We use express so this might be a problem with exress and the underlying network modules.

See https://github.com/expressjs/express/issues/4131#issuecomment-565655526 and https://github.com/expressjs/express/issues/3040 regarding the recommended solution `--max-http-header-size`.

**Comment by DanielRuf** [comment] 2019-12-28 18:01
Was your issue resolved by applying the change from your last comment?

> using `roleTypes` reduces the number of groups now:

**Comment by ViceIce** [comment] 2019-12-30 11:51
Yes, but now i can't use the extended features of `bitbucket-server` auth plugin, like allow access by project membership.

**Comment by DanielRuf** [comment] 2019-12-30 12:03
> See [expressjs/express#4131 (comment)](https://github.com/expressjs/express/issues/4131#issuecomment-565655526) and [expressjs/express#3040](https://github.com/expressjs/express/issues/3040) regarding the recommended solution `--max-http-header-size`.

Did you already try these solutions? Not sure if and how we can solve that directly in verdaccio.

**Comment by ViceIce** [comment] 2019-12-30 12:05
Not yet, sorry. Have a lot of other work to do. Maybe i can try it next year (begining).

**Comment by DanielRuf** [comment] 2019-12-30 12:08
Sounds good. Please let us know then what we can do to prevent or help others with this issue in the future (either by documenting it or solving it in verdaccio).

**Closed** 2020-02-16 12:03 UTC
Labels: issue: waiting-user-feedback

**Comment by haritonstefan** [comment] 2020-02-17 02:32
@juanpicado 
Hi, was there a PR solving this issue or another issue having more details? I'd like to be posted regarding this issue. To either know I can pick it up if I have free time, or if someone else already solved it.

Thanks.

**Comment by juanpicado** [comment] 2020-02-17 07:48
I don’t see a bug here, for such reason I closed it. But if you can provide a reproducible example, I would be happy to reopen it and merge your bug fix 👍
