### ISSUE TITLE
Other private npm solutions

### ISSUE THREAD

**Issue by skosno** [verdaccio/verdaccio#79] opened 2016-10-28 07:37 UTC
Hi,

First, thanks for your active work on maintaining sinopia!

We are currently looking in my company at possible solutions for private npm/npm cache and of course verdaccio/sinopia is being considered. At the same time we found some alternatives that seems to be actively used by others:
- Nexus 3: https://books.sonatype.com/nexus-book/3.0/reference/npm.html
- CNPM: https://github.com/cnpm/cnpmjs.org
- Artifactory: https://www.jfrog.com/confluence/display/RTF/Npm+Registry

Is anyone using/considering one of those?

**Comment by rmg** [comment] 2016-10-28 18:06
I've tried artifactory, but it doesn't handle being used as a staging registry for packages that eventually get published to npmjs.org. The problem comes up when you publish package@1.2.3 to it and then later publish package@1.2.3 to npmjs.org. When you go to install from it later it uses the metadata from npmjs.org, including the shasum, but the actual tarball is fetched from it's internal storage. Unless you jump through some hoops and bypass the normal `npm publish` flow, the tarballs will not be identical so you end up getting a permanent shasum mismatch.

**Comment by juanpicado** [comment] 2017-02-04 08:03
Closing, is not a bug, but keep the discussion, good to know about more alternatives

**Closed** 2017-02-04 08:02 UTC

**Comment by matiaslarsson** [comment] 2017-04-10 12:52
https://github.com/craftship/codebox-npm (Used to be called [Yith](https://craftship.io/open/source/serverless/private/npm/registry/yith/2016/09/26/serverless-yith.html))

**Comment by juanpicado** [comment] 2017-04-13 20:15
@matiaslarsson done 👍
