### ISSUE TITLE
Error: EPERM: operation not permitted, unlink on npm install

### ISSUE THREAD

**Issue by zentoaku** [verdaccio/verdaccio#1265] opened 2019-03-26 07:01 UTC
**Describe the bug**
I'm getting the following error when running npm install:
```npm ERR! path C:\projects\my-project\node_modules\.staging\typescript-dbc2289d\lib\typescriptServices.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\projects\my-project\node_modules\.staging\typescript-dbc2289d\lib\typescriptServices.js'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\projects\my-project\node_modules\.staging\typescript-dbc2289d\lib\typescriptServices.js']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\projects\my-project\node_modules\.staging\typescript-dbc2289d\lib\typescriptServices.js'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'C:\\projects\\my-project\\node_modules\\.staging\\typescript-dbc2289d\\lib\\typescriptServices.js' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'C:\\projects\\my-project\\node_modules\\.staging\\typescript-dbc2289d\\lib\\typescriptServices.js\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'C:\\projects\\my-project\\node_modules\\.staging\\typescript-dbc2289d\\lib\\typescriptServices.js',
npm ERR!   parent: 'my-project' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
```

My .npmrc:
```registry=https://my-domain:4873/
cafile=C:\Users\xxx\ca.pem
@xxx:registry=https://my-domain:4873/
@yyy:registry=https://my-domain:4873/
package-lock=false
//my-domain:4873/:_authToken="some-token-string"
```

I'm running Verdaccio 3.11.6 through official Docker image using below configuration file:

Sometimes "npm login" solves it for a moment (as described in other similar issues) but later on it comes back. Tried all other possibilities found here on on stackoverflow.

**To Reproduce**
1. Set everything as described above.
2. Run npm install.
3. See error

**Expected behavior**
Packages installed correctly.

**Docker (please complete the following information):**
 - Docker verdaccio tag: latest
 - Docker Version 17.05.0-ce

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
```storage: /verdaccio/storage
http_proxy: http://xxx:yyy@my-domain:8080/
https_proxy: http://xxx:yyy@my-domain:8080/
no_proxy: localhost,127.0.0.1,my-domain

https:
  key: /verdaccio/conf/my-domain.key
  cert: /verdaccio/conf/my-domain.crt
  ca: /verdaccio/conf/my-domain.csr

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
#    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: false
packages:
  '@xxx/*':
    # scoped packages
    access: $all
    publish: $authenticated
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    # publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  - {type: file, path: verdaccio.log, level: info}
middlewares:
  audit:
    enabled: true


max_body_size: 200mb
```

**Debugging output**  -  How to use it with docker?

 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:

**Comment by juanpicado** [comment] 2019-03-26 08:14
hi @zentoaku, this seems not related with Verdaccio, the error `npm ERR! syscall unlink` is a client tool error. I'd rather ask to the `npm` community for help.

**Comment by zentoaku** [comment] 2019-03-26 08:15
NPM doesn't have such issues. Only when Verdaccio is brought into equation I'm experiencing those. Also as I've wrote the solution with "npm login", which clearly affects something in Verdaccio flow, solves it sometimes.

**Comment by juanpicado** [comment] 2019-03-26 08:20
Then I'd suggest you dive more into it, more debugging in the client side and server side log to evaluate whether might be the issue. Also try with other tools as `yarn` or `pnpm` to discard is a `npm` issue also helps.

**Comment by zentoaku** [comment] 2019-04-01 06:24
fyi: did a quick check using yarn and installation went fine. Need to make couple more tests to make sure how the tool affects the flow.

**Comment by githoniel** [comment] 2019-04-03 06:47
i met this very often.
it is anoy.
Update npm to latest does not help. and there is no file ocuupy.

**Comment by adil-boukdair** [comment] 2019-04-18 08:16
restarting my computer solved it, i think an npm process is still runing and blocking access to node_modules folder.

**Comment by danieldanielecki** [comment] 2019-04-24 11:18
It could be simply due to the reason you had opened node_modules in file explorer.

**Comment by handyzhang** [comment] 2019-05-06 06:47
How did you do it?

**Comment by danieldanielecki** [comment] 2019-05-06 07:53
@handyzhang in my case my VPN blocked sharing C:\ with Docker, when turned off VPN it worked fine.

**Comment by handyzhang** [comment] 2019-05-07 01:50
vpn off，but....no use.

because some plugins are in the private library Verdaccio，so i will switched 'Verdaccio url'。
Plug-ins that do not load “Verdaccio url” and npm registry to “tao bao”or“npm”,this is right.
but if you switch to “Verdaccio url” from the beginning registry switched,this will “operation not permitted”.

now,Load NPM first and Ver again is no problem。

but I don't think that's going to solve the fundamental problem.

**Comment by danieldanielecki** [comment] 2019-05-07 10:13
Not using Verdaccio, sorry. The other thing it could be antivirus with its security policies.

**Comment by zentoaku** [comment] 2019-06-03 08:55
New finding regarding that issue: 
If I disable https in Verdaccio and simplify the .npmrc the issue is gone. By simplifying the .npmrc I mean:
OLD:
```
registry=https://my-verdaccio:4873/
cafile=C:\some-path\My-Custom-CA.pem
@xxx:registry=https://my-verdaccio:4873/
```
NEW:
```
registry=https://registry.npmjs.org/
@xxx:registry=http://my-verdaccio:4873/
```

**Comment by DanielRuf** [comment] 2019-06-04 15:07
In general this can happen if something else has open handles on the affected files. For example antivirus.

Verdaccio itself does not touch your local node_modules directory.

Can you provide a full reproducible testcase with the needed setup as repository (config example, Node and npm version, logfile without private details)?

**Comment by zentoaku** [comment] 2019-06-06 12:16
@DanielRuf It may take me some time to prepare proper test case but I will try my best (overloaded with work). I think the hardest thing will be to describe the configuration for development machines. It's enterprise setup, centrally managed so I don't know all the details. Can do a lot but there are some limitations. What I will try to provide at least is a couple more details in addition to what is in original description. Which logfile you have in mind?

**Comment by DanielRuf** [comment] 2019-06-06 12:23
Hi @zentoaku,

normally npm creates an error log when such things happen. There is also a `verbose` and `silly` logging level.

**Comment by himansishah** [comment] 2019-06-08 07:52
I am facing the same issue. I hope formatting PC and installing everything from scratch can be helpful.

**Comment by paul-mcnamee** [comment] 2019-06-28 19:21
This error is somewhat cryptic and for me it was occurring when a process was actively running. Closing running processes or perhaps just rebooting the machine should resolve this issue.

**Comment by theblindprophet** [comment] 2019-08-01 12:36
Had this exact issue when using Verdaccio, though I think it would have happened with any private registry. I removed the `.npmrc` file from my home directory.

I was then able to globally install all the packages I needed. After such, I added the `.npmrc` back.

**Comment by bbb159** [comment] 2019-09-06 19:47
I had the same problem and tried a lot of different things. This solved my problem:

1 - Uninstall NodeJs
2 - Delete folders 'npm' and 'npm-cache' from AppData/Roaming
3 - Deactivate firewall and all antivirus (including Windows Defender)
4 - Reboot the system
5 - Open command prompt as administrator and execute 'npm install'

**Comment by Haritsinh** [comment] 2019-10-10 05:50
Sometimes opened `IDE` or `Editor`  is the problem of failing installation,
 if you have opened `VSCode` while installing via `npm` then try closing the `VSCode` or any other `IDE` and try to run the npm command again, it worked in my case.

**Closed** 2019-10-13 08:13 UTC
Labels: external-issue, issue: need-more-info

**Comment by andrade-lucas** [comment] 2019-11-03 13:08
In my case it was been blocked by my computer's firewall, so I turned it off and it solved my problem.
