### ISSUE TITLE
Moving Verdaccio to another new server

### ISSUE THREAD

**Issue by sathishchandran97** [verdaccio/verdaccio#1318] opened 2019-05-20 10:55 UTC
I need to move the entire verdaccio to the new server. Is there any way to move the entire storage folder to new server.?

**Comment by sergiohgz** [comment] 2019-05-20 11:11
@sathishchandran97  If both servers can connect with SSH, you can SCP the storage folder. Later you have to ensure that Verdaccio storage configuration is pointing to the folder you want and probably restart the Verdaccio service.
Another way you can do is using [this tool](https://www.npmjs.com/package/pkgmigr8or), but having access to both servers I prefer the option before.
If this doesn't solve your problem, please, tell us more details (an example, if you are moving from local server to AWS and want to use S3 as storage) :wink:

**Comment by sathishchandran97** [comment] 2019-05-21 05:52
Hi @sergiohgz , I have tried moving storage folder. And I have copied entire storage folder to new server. But it didn't work for me. Is there any other file i should change?

**Comment by juanpicado** [comment] 2019-05-21 05:53
@sathishchandran97 if you share the specific issue perhaps we can find the answer. Also, we have a migration guide which might be helpful to read 

https://verdaccio.org/blog/2019/02/24/migrating-verdaccio

**Comment by sathishchandran97** [comment] 2019-05-21 05:58
Hi @juanpicado , I have my verdaccio on old server. Now we are migrating to new server. So i have to setup the verdaccio on new server. And i have configured verdaccio. But the issue is i have to publish around 110 components, and each have 10 versions, It will take long time if i publish one by one. So is there any way to move all the components to new verdaccio instead of publishing one by one.

**Comment by juanpicado** [comment] 2019-05-21 06:13
I think Sergio suggested the soution, copy the whole storage folder to the new location, plug and play. If that does not work please check whether paths are correct and folder permissions

**Comment by sathishchandran97** [comment] 2019-05-21 06:30
@juanpicado I have tested with one package. I moved 1 component to the storage folder and added the component name in .sinopia-db.json file and restarted verdaccio. But the new package didn't get reflected

**Comment by juanpicado** [comment] 2019-05-21 06:50
Ok, but still you need to share more info, remember you are the owner of your environment and I only know what you share here, follow this:

- Describe exactly your environment
- Share verdaccio version (`verdaccio --version`)
- Share config file (be careful and remove sensitive data)
- Describe the exactly steps and how to reproduce it locally.

 If you run `verdaccio` you can see the location of your config file, the version, url and port. 

```
➜  $ verdaccio
 warn --- config file  - /Users/{USER}/.config/verdaccio/config.yaml
 warn --- Plugin successfully loaded: verdaccio-htpasswd
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- http address - http://0.0.0.0:8081/ - verdaccio/4.0.0-beta.6
````

**Comment by sathishchandran97** [comment] 2019-05-21 08:10
@juanpicado I'm working on centos 7. 
verdaccio v3.2.0
Old server is also centos 6. Need to setup the verdaccio as like in old server. 
The problem is Old verdaccio is having multiple packages with multiple version. If i publish one by one means it will take long time. So is there any alternate way to move packages instead of publishing.

**Comment by juanpicado** [comment] 2019-05-21 08:27
> If i publish one by one means it will take long time. So is there any alternate way to move packages instead of publishing.

I'd suggest read again what @sergiohgz wrote above https://github.com/verdaccio/verdaccio/issues/1318#issuecomment-493942555

You only need to **copy the storage folder to a new location (server)**. That's all. Simple as it is. Have you tried that already? The storage folder looks like this one below.

![Screenshot 2019-05-21 at 10 27 19](https://user-images.githubusercontent.com/558752/58080224-0d0f9c00-7bb3-11e9-93f1-9fc8ba9c1923.png)


Important to highlight, **you do not need to publish them again**.

**Comment by sathishchandran97** [comment] 2019-05-21 08:35
Hi @juanpicado , Yes I have copied the entire storage folder. But still no packages reflected in verdaccio.
Do I need to configure anywhere else?

**Comment by juanpicado** [comment] 2019-05-21 08:39
The config file should reflect the new location for the storage. Then verdaccio can find the storage.

https://github.com/verdaccio/verdaccio/blob/master/conf/default.yaml#L10

```
storage: /newLocation/.local/share/verdaccio/storage
listen:
 - x.x.x.x:4873
````

This is all you need to set up, if it still does not work I'd suggest double check the paths, user permissions and so on. 

Closing this, since the answer is clear above :-)

**Closed by juanpicado** 2019-05-21 08:39 UTC
Labels: topic: question

**Comment by sathishchandran97** [comment] 2019-05-21 09:54
a
