### ISSUE TITLE
publisher's name field

### ISSUE THREAD

**Issue by sajadmirzaee** [verdaccio/verdaccio#1628] opened 2019-12-21 07:42 UTC
**Does it support publisher's name field? If yes, how could I use that? And if no, could this be legit feature request?**

![calc](https://user-images.githubusercontent.com/41946561/71305234-c783ad80-23e5-11ea-90d4-e2bf7177aae9.png)

**Comment by juanpicado** [comment] 2019-12-21 11:19
Yes, we do.

```
➜ npm info verdaccio --registry https://registry.verdaccio.org

verdaccio@4.4.0 | MIT | deps: 34 | versions: 150
A lightweight private npm proxy registry
https://verdaccio.org

bin: verdaccio

dist
.tarball: https://registry.verdaccio.org/verdaccio/-/verdaccio-4.4.0.tgz
.shasum: 10dcbbd40504a2ab19ad8ef71b1522623440ab65
.integrity: sha512-w1X6kjKazx7OtFb36algShiU/Zi9ihuGzpQHNEGmLB9e2Q3xHoZP44gGuOPCR91S9iCwfVA3yN3DtjZwITjK5A==
.unpackedSize: 998.3 kB

dependencies:
@verdaccio/commons-api: 8.3.0   async: 3.1.0                    cors: 2.8.5                     js-yaml: 3.13.1
@verdaccio/local-storage: 8.4.2 body-parser: 1.19.0             dayjs: 1.8.17                   jsonwebtoken: 8.5.1
@verdaccio/readme: 8.4.2        bunyan: 1.8.12                  envinfo: 7.5.0                  kleur: 3.0.3
@verdaccio/streams: 8.2.0       commander: 3.0.2                express: 4.17.1                 lockfile-lint: 2.0.1
@verdaccio/ui-theme: 0.3.9      compression: 1.7.4              handlebars: 4.5.3               lodash: 4.17.15
JSONStream: 1.3.5               cookies: 0.7.3                  http-errors: 1.7.3              lunr-mutable-indexes: 2.3.2
(...and 10 more.)

dist-tags:
feat-token: 4.3.0-pre-token  logger: 4.1.0-feat-pino-1    previous: 3.13.1
latest: 4.4.0                next: 4.0.0-beta.10

published 6 days ago by verdaccio.npm <verdaccio.npm@gmail.com>
```

Actually, verdaccio do not mutate any metadata, if you are getting undefined then you would need to share more info, please read https://raw.githubusercontent.com/verdaccio/verdaccio/master/.github/ISSUE_TEMPLATE/Bug_report.md

Also, try with other npm package mangers and try to the produce your issue with other registries might helpful.

**Comment by juanpicado** [comment] 2019-12-21 11:19
I'll close it since there is no much to add, feel free to report more info if you find out the problem is in our side 👍

**Closed by juanpicado** 2019-12-21 11:19 UTC
Labels: question

**Comment by sajadmirzaee** [comment] 2019-12-21 13:02
I asked about the modules
That are released locally by verdaccio, not the modules we release at npm
@juanpicado

**Comment by juanpicado** [comment] 2019-12-21 13:15
Then still not clear to me what is your question, please elaborate more.

**Comment by sajadmirzaee** [comment] 2019-12-21 13:55
When running verdaccio on a system in a local environment and publishing a module, the publisher name is unknown

@juanpicado

**Comment by sajadmirzaee** [comment] 2019-12-22 06:14
Another example I set up in my  own system

@juanpicado 

![sajad](https://user-images.githubusercontent.com/41946561/71318002-8d76e200-249f-11ea-8806-9f2b8e37f16c.png)

**Comment by DanielRuf** [comment] 2019-12-24 14:47
Please provide the exact steps how you did this and how you display this information.

**Comment by sajadmirzaee** [comment] 2019-12-24 15:18
Could you please tell us more precisely what information he wants from
@DanielRuf

**Comment by DanielRuf** [comment] 2019-12-24 15:22
@sajadmirzaee I do not know this information on your screenshots. Which tool or output from which exact command is this?

Your initial issue description does not contain any reproducible steps as requested in our issue template.

As @juanpicado already wrote, please use our issue template:
https://github.com/verdaccio/verdaccio/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md
