### ISSUE TITLE
Issue after migrating to last version of verdaccio docker container

### ISSUE THREAD

**Issue by ohardy** [verdaccio/verdaccio#336] opened 2017-10-01 08:31 UTC
I use verdaccio to cache official npm and with the last version, nothing work anymore. Sample of logs:

```
Error: EACCES: permission denied, open '/verdaccio/storage/babel-plugin-istanbul/package.json.tmp49661222414352046'
 http <-- 500, user: ohardy(82.226.182.238 via 172.17.0.1), req: 'GET /babel-plugin-istanbul', error: internal server error
 error--- unexpected error: EACCES: permission denied, open '/verdaccio/storage/babel-jest/package.json.tmp4694115279311166'
Error: EACCES: permission denied, open '/verdaccio/storage/babel-jest/package.json.tmp4694115279311166'
 http <-- 500, user: ohardy(82.226.182.238 via 172.17.0.1), req: 'GET /babel-jest', error: internal server error
 error--- unexpected error: EACCES: permission denied, open '/verdaccio/storage/babel-plugin-transform-builtin-extend/package.json.tmp014606603792043371'
Error: EACCES: permission denied, open '/verdaccio/storage/babel-plugin-transform-builtin-extend/package.json.tmp014606603792043371'
 http <-- 500, user: ohardy(82.226.182.238 via 172.17.0.1), req: 'GET /babel-plugin-transform-builtin-extend', error: internal server error
 error--- unexpected error: EACCES: permission denied, open '/verdaccio/storage/babel-plugin-react-transform/package.json.tmp03199536625295707'
Error: EACCES: permission denied, open '/verdaccio/storage/babel-plugin-react-transform/package.json.tmp03199536625295707'
 http <-- 500, user: ohardy(82.226.182.238 via 172.17.0.1), req: 'GET /babel-plugin-react-transform', error: internal server error
 error--- unexpected error: EACCES: permission denied, open '/verdaccio/storage/babel-cli/package.json.tmp7871270515137267'
Error: EACCES: permission denied, open '/verdaccio/storage/babel-cli/package.json.tmp7871270515137267'
....
```

**Comment by juanpicado** [comment] 2017-10-01 08:39
We haven't changed anything related to permissions in the last Docker image. Please clean your cache and try again.

**Comment by juanpicado** [comment] 2017-10-01 13:38
We have a new version at Docker, please upgrade and let us know whether it works or not

**Comment by ohardy** [comment] 2017-10-02 06:07
Fixed :) Thanks !

**Comment by ohardy** [comment] 2017-10-11 12:46
The issue is back :(

**Comment by juanpicado** [comment] 2017-10-11 16:36
@ohardy We need more detailed information about the issue. How to reproduce, etc etc.

**Comment by bochen2014** [comment] 2018-03-23 05:21
got the same issue

I'm using `verdaccio/verdaccio:latest`,  a `docker inspect` returns me
` "Image": "sha256:cab129e3f6f63e154a1cebafb057049b5f826476f29cf4a9de0a174628b60b4b",`
The command i used to start `verdaccio` is 
1. `docker create --name tmp  verdaccio/verdaccio`
2. `docker cp tmp:/verdaccio  /opt`  this will copy the `/verdaccio` fold out
3. I made a small change to `/opt/verdaccio/conf/config.yaml`, added `max_body_size:1000mb`
4. `docker run -d -v /opt/verdaccio:/verdaccio  -p 4873:4873 verdaccio/verdaccio`

and when I run `npm adduser --registry http://localhost:4873` I got error:

```
 error--- unexpected error: EACCES: permission denied, open '/verdaccio/conf/htpasswd'
Error: EACCES: permission denied, open '/verdaccio/conf/htpasswd'
 http <-- 500, user: undefined(172.17.0.1), req: 'PUT /-/user/org.couchdb.user:bo', error: internal server error
```

A further research on this problem: 
```bash
docker run --rm -v /opt/verdaccio/:/verdaccio  verdaccio/verdaccio  ls -l /verdaccio
total 8
drwxr-xr-x    2 node     node          4096 Mar 23 04:03 conf
drwxr-xr-x    2 node     node          4096 Jan 28 20:32 storage
```
so bind mount mounts `/verdaccio` as `node:node`; NOT `verdaccio:verdaccio` as described in .dockerfile.

Any idea??

**Comment by bochen2014** [comment] 2018-03-23 05:22
@juanpicado can you please re-open this issue? thanks

**Comment by juanpicado** [comment] 2018-03-23 05:24
Let's investiage.

**Comment by bochen2014** [comment] 2018-03-23 05:32
ok. I think there is something wrong in the `.dockerfile`. 

this is what did 
1. define a dockerfile (use the same pattern as in verdaccio)
```dockerfile
from busybox
RUN mkdir -p /verdaccio/storage /verdaccio/conf
RUN addgroup -S verdaccio && adduser -S -G verdaccio verdaccio && \
    chown -R verdaccio:verdaccio /verdaccio

USER verdaccio

CMD /bin/sh
```
2.  `docker build -t bo-busybox .`
3. `docker run --rm -it -v /opt/verdaccio:/verdaccio  bo-busybox`
```bash
    > cd /verdaccio/conf/
    > ls 
        config.ymla
    > touch test.log
       touch: test.log: Permission denied
 ```

**Comment by bochen2014** [comment] 2018-03-23 08:36
figured it out. see [this](https://github.com/docker-library/redis/issues/7#issuecomment-52240915)

reason is that when doing bind mount, docker wont' change the owner of the host dir.
in docker file, owner of `/verdaccio` is set to `verdaccio:verdaccio`(100:100), but on my host machine (a ubuntu), default user:group is 1000:1000 which is node:node in the container. 

if I do a `chown -R 100:101 /opt/verdaccio` everything will be fine

solution is to add a `chown` at ENTRYPOINT or, not user `USER` at all

**Comment by juanpicado** [comment] 2018-03-23 18:07
What is the different between gosu and https://github.com/Yelp/dumb-init approach? I'm not docker expert.

**Comment by juanpicado** [comment] 2018-03-23 19:57
I think this might be related https://github.com/verdaccio/verdaccio/issues/532

**Comment by bochen2014** [comment] 2018-03-24 10:36
sorry for the late response. 

my understanding of `gosu` and `dumb-init` is that they are totally two different things.
1. `gosu` is a go implementation of `sudo/su` , the purpose is to achieve `sudo/su` without all the messy configurations in different flavour of linux (e.g. setting up user shell). If you are familiar with the flavor of linux you are running on, you don't need `gosu`
2. `dumb-init` is designed to assume the init power process (pid=1),it's able to handle SIGTERM signals and make sure there won't be any orphaned process after container is terminated. 

I mentioned `gosu` in my previous post mostly because I was looking at `postgres`, `mysql` and `redis` and they all use `gosu` in their dockerfile (to achieve the purpose of running as an unprivileged user inside the docker container). so i just did a copy/paste. It's not necessary. I'm sure we can achieve the same by using `su`; 
the point is, `verdaccio` is using the `USER` command and it is causing issues that 
*when bind mount folder has a different owner:owner-group, docker user(verdaccio) has no permission to it*, that explains the `error--- unexpected error: EACCES: permission denied, open '/verdaccio/conf/htpasswd` I got before. 

per my research so far, the common practice is to **NOT** use `USER` command in dockerfile, so the docker container will always run as `root` user when its starts. To run your program as a non-root user, you need to 
1. do a `chown -R  verdaccio:verdaccio  /verdaccio` as first thing
2. `su verdaccio -s /bin/sh  -c 'verdaccio'` . Note here that I added `-s /bin/sh`, that is because the newly added user `verdaccio` has shell `/bin/false` assigned to it (you can run `cat /etc/passwd` to verify it). If we use `gosu`, we wont' need to get into these details, it just works

I also built up a small image to test my understanding
```dockerfile
FROM node:9.5.0-alpine
RUN mkdir -p /verdaccio/storage /verdaccio/conf
RUN addgroup -S verdaccio && adduser -S -G verdaccio   verdaccio 

COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh
CMD ["entrypoint.sh"]
```
```sh
#!/bin/sh
chown -R verdaccio:verdaccio /verdaccio 
# https://unix.stackexchange.com/a/39376/272227
# cat /etc/passwd to see the default sh
# if /bin/false, then the user is not allowed to login
su verdaccio -s /bin/sh -c 'touch /verdaccio/conf/htpasswd'
```

the side effect is that, say in my host I have a folder `/opt/verdaccio` 
before bind mount to  docker container
```bash
/opt/git/docker-playground$ ls -l /opt/verdaccio/
drwxrwxr-x 2 bochen2014 bochen2014 4096 Mar 24 21:23 conf
drwxrwxr-x 2 bochen2014 bochen2014 4096 Mar 24 20:28 storage
```
after bind mount to docker container
```bash
/opt/git/docker-playground$ ls -l /opt/verdaccio/
drwxrwxr-x 2 systemd-timesync systemd-journal 4096 Mar 24 21:30 conf
drwxrwxr-x 2 systemd-timesync systemd-journal 4096 Mar 24 20:28 storage
```
note that the owner of that folder is changed to `systemd-timesync:systemd-journal`. that's because insider docker `verdaccio:verdaccio` has `uid=101, gid=101`, which is mapped to that `systemd` user/group on my host machine. 

**CONCLUSION**
if the docker container is running as a non root user, don't use `bind mount` as you either 
1. run into permission issues as I'm having now
OR
2. have your bind mount folder owner changed 'unexpectly' as in the `postgres`/`mysql`/`redis` case

I can confirm that using `docker volume` won't run into this issue and therefore should be the recommended way. 

I think you can close this ticket as a 'known issue'

**Comment by juanpicado** [comment] 2018-03-24 11:04
Brilliant explanation. Do you think we should update docs in some way?

**Comment by bochen2014** [comment] 2018-03-24 11:13
maybe just drop a line saying : 
*since verdaccio runs as a non-root user (uid=101, gid=101)  inside the container, if you use bind mount to override the default config, you need to make sure the mount directory is assigned to the corresponding user. For example: if you want to mount `/opt/verdaccio` from your host as the `/verdaccio` in container ,you need to run `sudo chown -R 101:101 /opt/verdaccio` otherwise you will get permission errors at runtime*

**Comment by juanpicado** [comment] 2018-03-24 11:27
Thanks so much, If you want to PR :-) would be great.

**Comment by bochen2014** [comment] 2018-03-24 12:32
not a problem at all. [PR#635](https://github.com/verdaccio/verdaccio/pull/635) created. 

Thanks for building such a useful tool for the community :+1:

**Comment by juanpicado** [comment] 2018-03-24 12:50
Thanks @bochen2014 🥇

**Closed by juanpicado** 2018-03-24 12:50 UTC
Labels: Docker, Fixed, need review

**Comment by omaskery** [comment] 2018-05-03 11:05
I have just tried running the verdaccio/verdaccio:3.0.0-beta.7 docker image and run into this issue. I followed the advice of `chown`'ing the `/opt/verdaccio` directory to 101:101 and still had permission errors. I then used `docker exec -it verdaccio sh` to enter the container and used `ls -alhn` to see what IDs the container expected on various files. I noticed that 100:101 is prevalent, and so tried `chown -R 100:101 /opt/verdaccio` on the host machine and now I don't get permission errors.

Should the documentation suggest `chown`'ing to 100:101, or have I done something strange?

**Comment by bochen2014** [comment] 2018-05-03 12:11
yep. i think I made a typo before. It was 100:101

**Comment by bochen2014** [comment] 2018-05-03 12:13
actually the docker file only says `RUN addgroup -S verdaccio && adduser -S -G verdaccio verdaccio && \ so the system will always allocate the next available id for it; 
it could be 100:101 and 200:201 going forward. . 

again, I don't think it's good idea to bind mound your local folder to the container; using docker volume is a better approach

**Comment by juanpicado** [comment] 2018-05-03 18:17
Do you think we can improve the documentation in a way people to not get confuse with this topic ?

**Comment by omaskery** [comment] 2018-05-03 18:31
Thanks to both of you for replying so soon!

To be clear: I think the documentation makes perfectly clear that `docker volume` is a better approach, it's just that unfortunately the network I work on is still using docker 1.8 (😱)! I believe I therefore have to use bind mount, which lead me to the ownership problem as discussed.

The only documentation change I would recommend is that [this page in the documentation, that currently suggests setting both the user & group to 101](https://www.verdaccio.org/docs/en/docker.html#running-verdaccio-using-docker), should say to set the user to 100 and the group 101. This way people who have docker >1.8 will still see the advice about using `docker volume`, and lost souls like me on docker <=1.8 will have working instructions for bind mount 😄

To be specific, the note with the red background could be changed as such:
```diff
Note: Verdaccio runs as a non-root user (uid=101, gid=101) inside the container, if you use bind
mount to override default, you need to make sure the mount directory is assigned to the right user.
-In above example, you need to run sudo chown -R 101:101 /opt/verdaccio otherwise you will
+In above example, you need to run sudo chown -R 100:101 /opt/verdaccio otherwise you will
get permission errors at runtime. Use docker volume is recommended over using bind mount.
```
