### ISSUE TITLE
Long installation of packages

### ISSUE THREAD

**Issue by Tixxxon** [verdaccio/verdaccio#2069] opened 2021-01-23 08:24 UTC
When installing packages, if there are many other packages in node_modules instead of installing one, does verdaccio start checking all the other packages? It takes forever. Is there any way to fix this?

**Comment by juanpicado** [comment] 2021-01-23 08:28
Hi @Tixxxon 

This is how Node.js works, I would rather find more information about dependencies in any blog or official docs, tutorial etc. 

I close this, not a bug.

**Closed by juanpicado** 2021-01-23 08:28 UTC
