### ISSUE TITLE
Verdaccio is not storing the packages in local repo

### ISSUE THREAD

**Issue by adnanjee** [verdaccio/verdaccio#1101] opened 2018-10-31 07:54 UTC
Here are some of my logs. I think vardaccio is not storing packages but always download it and transfer it. It always shows bytes: 0/3789. I have installed same package on many systems.
```
http <-- 200, user: null(192.168.1.252), req: 'GET /on-finished/-/on-finished-2.3.0.tgz', bytes: 0/4552
 http <-- 200, user: null(192.168.1.252), req: 'GET /fresh/-/fresh-0.3.0.tgz', bytes: 0/2472
 http <-- 200, user: null(192.168.1.252), req: 'GET /parseurl/-/parseurl-1.3.2.tgz', bytes: 0/3789
 http <-- 200, user: null(192.168.1.252), req: 'GET /methods/-/methods-1.1.2.tgz', bytes: 0/2475
 http <-- 200, user: null(192.168.1.252), req: 'GET /proxy-addr/-/proxy-addr-1.0.10.tgz', bytes: 0/4935
 http <-- 200, user: null(192.168.1.252), req: 'GET /range-parser/-/range-parser-1.0.3.tgz', bytes: 0/2462
```

**Comment by juanpicado** [comment] 2018-10-31 10:51
Please provide more info about your evrionment, config file and all is helpful for us to help you.

**Comment by adnanjee** [comment] 2018-10-31 11:17
I have installed it on Ubuntu 16.04 Lts using npm. Default configuraion file. I have only add two lines at the end of the configuration file to listen it on 0.0.0.0:4873.

**Comment by adnanjee** [comment] 2018-11-19 04:34
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /home/cache/.local/share/verdaccio/storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
listen:
  - 0.0.0.0:4873

**Comment by juanpicado** [comment] 2018-11-19 05:44
I don't see anything wrong with the info you have provided, I'm closing this due I think you have some sort of permissions issue. I'll reopen if you provide more info that proves the issue is in our side. Thanks for reporting,

**Closed by juanpicado** 2018-11-19 05:44 UTC
Labels: invalid, waiting-user-feedback
