### ISSUE TITLE
Can't login with htpasswd from old sinopia

### ISSUE THREAD

**Issue by smelukov** [verdaccio/verdaccio#762] opened 2018-06-15 12:25 UTC
**Describe the bug**
We're migrating from old sinopia. Just used htpasswd file from sinopia and got a problem with login

**To Reproduce**
- get htpasswd file from sinopia and use it in verdaccio
- try to login
- get an error
```
npm ERR! code EAUTHIP
npm ERR! Unable to authenticate, need: Basic, Bearer
```

**Expected behavior**
Correct authentification

**Comment by juanpicado** [comment] 2018-06-15 12:48
@ayusharma it happened to me this week. This one is important.

**Comment by ayusharma** [comment] 2018-06-15 13:04
I am not able to reproduce it.

What I did:

1. Installed sinopia.
2. Created some users using `npm adduser` in sinopia.
3. Copied `sinopia`'s htpasswd file to `verdaccio`'s htpasswd file.
4. Tried to log in in both CLI and web view. Everything is working fine for me.

I am sharing my dummy htpasswd file (created using sinopia):
```
test:{SHA}qUqP5cyxm6YcTAhz05Hph5gvu9M=:autocreated 2018-06-15T12:42:19.005Z
tom:{SHA}loNd2L+nGL1kR8zIevia4Wddrso=:autocreated 2018-06-15T12:54:26.029Z
```
- Password for `test` user is `test`.
- Password for `tom` uset is `tom`.

@juanpicado Could you please give a try again.

**Comment by juanpicado** [comment] 2018-06-15 16:19
@ayusharma I'll also try. But I saw the same error, it might be misleading message from `npm`. We should try also with `yarn`

**Comment by juanpicado** [comment] 2018-06-15 18:21
For some reason, `npm` catch 401 HTTP error as that misleading message. I'm forcing my user with wrong password. 
```
➜ npm --version
6.1.0
➜ npm adduser --registry http://localhost:4873 -ddd

npm http request → PUT http://localhost:4873/-/user/org.couchdb.user:jpicado
npm http 401 ← Unauthorized (http://localhost:4873/-/user/org.couchdb.user:jpicado)
npm verb stack Error: Unable to authenticate, need: Basic, Bearer
```
while with 
```
➜ npm --version           
5.0.0
➜ npm adduser --registry http://localhost:4873 -ddd
4873" "-ddd"
npm verb node v9.9.0
npm verb npm  v5.0.0
npm ERR! code E401
npm ERR! unauthorized access : -/user/org.couchdb.user:jpicado
npm verb exit [ 1, true ]
``

**Comment by juanpicado** [comment] 2018-06-15 18:36
Have you seen this before @ayusharma ? https://github.com/npm/npm-profile/blob/latest/lib/index.js#L367

Either headers must contains either OTP (One Time Password Authentication ?? 😕 ) or `ipaddress` becames `HttpErrorAuthUnknown` ??????? .. 👎  ...

**Comment by ayusharma** [comment] 2018-06-16 09:34
@juanpicado I'll see this.

**Comment by ayusharma** [comment] 2018-06-16 11:39
NPM Version:
```
npm  -v
6.1.0
```

NPM Logs:
```
npm adduser --registry http://localhost:4873 -ddd

npm info it worked if it ends with ok
npm verb cli [ '/Users/ayushsharma/.nvm/versions/node/v10.4.1/bin/node',
npm verb cli   '/Users/ayushsharma/.nvm/versions/node/v10.4.1/bin/npm',
npm verb cli   'adduser',
npm verb cli   '--registry',
npm verb cli   'http://localhost:4873',
npm verb cli   '-ddd' ]
npm info using npm@6.1.0
npm info using node@v10.4.1
npm verb npm-session 86570d3105ea2220
npm verb web login before first POST
npm http request → POST http://localhost:4873/-/v1/login
npm http 404 ← Not Found (http://localhost:4873/-/v1/login)
npm verb web login not supported, trying couch
Username: joe
Password:
Email: (this IS public) joe@joe.com
npm verb login before first PUT { _id: 'org.couchdb.user:joe',
npm verb login   name: 'joe',
npm verb login   password: 'XXXXX',
npm verb login   type: 'user',
npm verb login   roles: [],
npm verb login   date: '2018-06-16T11:36:43.389Z' }
npm http request → PUT http://localhost:4873/-/user/org.couchdb.user:joe
npm http 201 ← Created (http://localhost:4873/-/user/org.couchdb.user:joe)
npm info login Authorized user joe
Logged in as joe on http://localhost:4873/.
npm verb exit [ 0, true ]
npm timing npm Completed in 30427ms
npm info ok
```

Verdaccio's logs:
```
yarn run dev:start --inspect
yarn run v1.7.0
$ cross-env BABEL_ENV=registry babel-node src/lib/cli --inspect
Debugger listening on ws://127.0.0.1:9229/9d4a7a59-4842-48d8-9e88-ffdd610842cf
For help see https://nodejs.org/en/docs/inspector
 warn --- config file  - /Users/ayushsharma/.config/verdaccio/config.yaml
 warn --- Plugin successfully loaded: htpasswd
 warn --- Plugin successfully loaded: audit
 warn --- http address - http://localhost:4873/ - verdaccio/3.2.0
Debugger attached.
 http <-- 404, user: undefined(127.0.0.1), req: 'POST /-/v1/login', bytes: 32/150
 http <-- 201, user: joe(127.0.0.1), req: 'PUT /-/user/org.couchdb.user:joe', bytes: 119/72
```

**Comment by juanpicado** [comment] 2018-06-16 13:36
let's wait @smelukov feedback, but I think is not a verdaccio issue.

**Comment by marcellodesales** [comment] 2018-06-19 02:02
I'm getting the same problem with the current code with volumes...

@smelukov @juanpicado @ayusharma any way I can get this working with npm 6 and node 10?

# Started the server

```
$ docker-compose up -d
$ docker-compose ps
                Name                              Command               State           Ports
------------------------------------------------------------------------------------------------------
verdaccio-3-docker-local-storage-vol   /usr/local/bin/dumb-init - ...   Up      0.0.0.0:4873->4873/tcp
```

# User setup

* Added the user

```
$ npm adduser --registry http://localhost:4873 -ddd
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'adduser',
npm verb cli   '--registry',
npm verb cli   'http://localhost:4873',
npm verb cli   '-ddd' ]
npm info using npm@6.1.0
npm info using node@v10.4.1
npm verb npm-session aa8fd023a3f60bec
npm verb web login before first POST
npm http request → POST http://localhost:4873/-/v1/login
npm http 404 ← Not Found (http://localhost:4873/-/v1/login)
npm verb web login not supported, trying couch
Username: mdesales
Password:
Email: (this IS public) marcello.desales@gmail.com
npm verb login before first PUT { _id: 'org.couchdb.user:mdesales',
npm verb login   name: 'mdesales',
npm verb login   password: 'XXXXX',
npm verb login   type: 'user',
npm verb login   roles: [],
npm verb login   date: '2018-06-19T01:54:01.768Z' }
npm http request → PUT http://localhost:4873/-/user/org.couchdb.user:mdesales
npm http 201 ← Created (http://localhost:4873/-/user/org.couchdb.user:mdesales)
npm info login Authorized user mdesales
Logged in as mdesales on http://localhost:4873/.
npm verb exit [ 0, true ]
npm timing npm Completed in 19936ms
npm info ok
```

* I can see the config changed through the local volume dir

```
$ cat conf/htpasswd
mdesales:$6mgo0Y5YuBsk:autocreated 2018-06-19T01:54:01.851Z
```

* I can see the `.npmrc` file with the entry for the config

```
$ cat ~/.npmrc
//registry-qal.npmjs.company.net/:_authToken=ad37a2d-------ee6d2497e060fc77ea4c8
//localhost:4873/:_authToken="ovOyjvtmM8yOSLgTU/E43buKAkFwBOMACUzGGxzaDBI="
```

* I noticed that npm 6 surrounds the token with `"`

# Trying to publish

It fails and keeps saying it cannot publish to add a new user `npm ERR! need auth You need to authorize this machine using "npm adduser"`

```
$ npm publish --registry http://localhost:4873
npm info it worked if it ends with ok
npm info using npm@6.1.0
npm info using node@v10.4.1
npm info lifecycle @devportalx/config-addon@0.9.22~prepublish: @devportalx/config-addon@0.9.22
npm info lifecycle @devportalx/config-addon@0.9.22~prepare: @devportalx/config-addon@0.9.22
npm info lifecycle @devportalx/config-addon@0.9.22~prepublishOnly: @devportalx/config-addon@0.9.22
npm info lifecycle @devportalx/config-addon@0.9.22~prepack: @devportalx/config-addon@0.9.22
npm info lifecycle @devportalx/config-addon@0.9.22~postpack: @devportalx/config-addon@0.9.22
npm notice
npm notice 📦  @devportalx/config-addon@0.9.22
npm notice === Tarball Contents ===
npm notice 3.1kB  package.json
npm notice 103B   .babelrc
npm notice 668B   .eslintrc.js
npm notice 828B   build.js
npm notice 1.5kB  COMMUNITY.md
npm notice 399B   CONTRIBUTING.md
npm notice 247B   docker-compose.yaml
npm notice 11.6kB README.md
npm notice 1.3kB  Troubleshooting.md
npm notice 3.2kB  webpack.config.js
npm notice 10.9kB lib/components/Addon.js
npm notice 17.3kB lib/components/ConceptUseCases.js
npm notice 22.6kB lib/components/IncompleteOnboarding.js
npm notice 9.4kB  lib/components/NotOnboarded.js
npm notice 5.1kB  lib/components/onboardings/DeleteOnboardingButton.js
npm notice 15.8kB lib/components/onboardings/incomplete/ApplicationNameSelection.js
npm notice 6.4kB  lib/components/onboardings/incomplete/GithubAuthentication.js
npm notice 9.2kB  lib/components/onboardings/incomplete/GithubOrgRepoSelection.js
npm notice 11.1kB lib/components/onboardings/incomplete/SelectionConfirmation.js
npm notice 3.9kB  lib/components/onboardings/Onboarding.js
npm notice 5.8kB  lib/components/onboardings/OnboardingAccessLevel.js
npm notice 6.9kB  lib/components/onboardings/OnboardingConfigServer.js
npm notice 5.7kB  lib/components/onboardings/OnboardingEnvironment.js
npm notice 7.4kB  lib/components/onboardings/OnboardingGithubRepo.js
npm notice 6.2kB  lib/components/onboardings/OnboardingInspector.js
npm notice 5.7kB  lib/components/onboardings/OnboardingPublisher.js
npm notice 17.1kB lib/components/onboardings/Onboardings.js
npm notice 16.0kB lib/components/onboardings/OnboardingsContainer.js
npm notice 10.2kB lib/components/Welcome.js
npm notice 6.6kB  lib/conf.js
npm notice 2.2kB  lib/data/794902926525913686.json
npm notice 304B   lib/index.js
npm notice 12.7kB lib/services/ConfigManagerService.js
npm notice 2.2kB  lib/services/DeveloperService.js
npm notice 7.1kB  lib/services/HttpService.js
npm notice 6.3kB  src/components/Addon.js
npm notice 7.1kB  src/components/ConceptUseCases.js
npm notice 16.7kB src/components/IncompleteOnboarding.js
npm notice 3.4kB  src/components/NotOnboarded.js
npm notice 2.1kB  src/components/onboardings/DeleteOnboardingButton.js
npm notice 7.5kB  src/components/onboardings/incomplete/ApplicationNameSelection.js
npm notice 2.8kB  src/components/onboardings/incomplete/GithubAuthentication.js
npm notice 4.4kB  src/components/onboardings/incomplete/GithubOrgRepoSelection.js
npm notice 4.6kB  src/components/onboardings/incomplete/SelectionConfirmation.js
npm notice 1.1kB  src/components/onboardings/Onboarding.js
npm notice 2.1kB  src/components/onboardings/OnboardingAccessLevel.js
npm notice 2.3kB  src/components/onboardings/OnboardingConfigServer.js
npm notice 2.3kB  src/components/onboardings/OnboardingEnvironment.js
npm notice 2.7kB  src/components/onboardings/OnboardingGithubRepo.js
npm notice 2.6kB  src/components/onboardings/OnboardingInspector.js
npm notice 1.8kB  src/components/onboardings/OnboardingPublisher.js
npm notice 11.9kB src/components/onboardings/Onboardings.js
npm notice 10.7kB src/components/onboardings/OnboardingsContainer.js
npm notice 3.5kB  src/components/Welcome.js
npm notice 5.9kB  src/conf.js
npm notice 2.2kB  src/data/794902926525913686.json
npm notice 63B    src/index.js
npm notice 10.3kB src/services/ConfigManagerService.js
npm notice 559B   src/services/DeveloperService.js
npm notice 4.0kB  src/services/HttpService.js
npm notice === Tarball Details ===
npm notice name:          @devportalx/config-addon
npm notice version:       0.9.22
npm notice package size:  66.3 kB
npm notice unpacked size: 365.6 kB
npm notice shasum:        c015d4b7d9a827b863204505fcbf0068cb6577b7
npm notice integrity:     sha512-vCuHdlLx4tgTr[...]3SYSIHcZ3HvDA==
npm notice total files:   60
npm notice
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
npm timing npm Completed in 1089ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mdesales/.npm/_logs/2018-06-19T01_58_47_183Z-debug.log
```

**Comment by juanpicado** [comment] 2018-06-19 11:58
> I'm getting the same problem with the current code with volumes...

It seems a different main topic and your issue are different. Are you migrating from sinopia?

> I noticed that npm 6 surrounds the token with "

npm does not wrap the token, it's delivered by verdaccio in that way, please read  https://github.com/verdaccio/verdaccio/issues/168#issuecomment-394149624

> The package.json lists registry as another value

I'll need a clarification here.

> The logs from /Users/mdesales/.npm/_logs/2018-06-19T01_58_47_183Z-debug.log ..

I suggest more verbose (extreme) there `npm publish --registry http://localhost:4873 -ddd`

> Replacing the registry value with http://localhost:4873 worked.

🤔

**Comment by juanpicado** [comment] 2018-06-19 11:58
@smelukov ping 🤓

**Comment by smelukov** [comment] 2018-06-19 13:36
> I'll diff the passwords from old an new file only on Monday
oh, i'm sorry...
There are different hashes for the same password:
verdaccio:
`smelyukov:$606...........:autocreated 2018-06-14T13:37:41.898Z`
sinopia
`smelyukov:{SHA}yq2..............=:autocreated 2017-08-09T08:57:46.734Z`

**Comment by ayusharma** [comment] 2018-06-19 13:41
@smelukov It should not create any problem. We've handled this. 

I have both the hashed in `htpasswd` file, and I am able to log in for all of the users.

```
test:{SHA}qUqP5cyxm6YcTAhz05Hph5gvu9M=:autocreated 2018-06-15T12:42:19.005Z
tom:{SHA}loNd2L+nGL1kR8zIevia4Wddrso=:autocreated 2018-06-15T12:54:26.029Z
dev:$6EjNiSpohSqs:autocreated 2018-06-16T11:16:37.289Z
joe:$67OJow.lyntw:autocreated 2018-06-16T11:36:43.405Z
sam:$6zuE.YJk7VE6:autocreated 2018-06-16T13:20:16.593Z
```

**Comment by smelukov** [comment] 2018-06-19 13:45
> We've handled this.

from which version? 🤔

**Comment by ayusharma** [comment] 2018-06-19 13:53
> from which version? 🤔

It is available here .
https://github.com/verdaccio/verdaccio-htpasswd/blob/36ef763f1ac9b83ba09d639fe9c41d5ffbbfa230/src/utils.js#L50

It is in verdaccio 3 and all versions of  [verdaccio-htpasswd](https://github.com/verdaccio/verdaccio-htpasswd)

**Comment by smelukov** [comment] 2018-06-19 14:01
Seems like some kind of magic, but authentification with old htpasswd does not work for us.
If you can not reproduce it then maybe issue must be closed 🤔

**Comment by juanpicado** [comment] 2018-06-19 20:52
> oh, i'm sorry...
There are different hashes for the same password:
verdaccio:
smelyukov:$606...........:autocreated 2018-06-14T13:37:41.898Z
sinopia
smelyukov:{SHA}yq2..............=:autocreated 2017-08-09T08:57:46.734Z

@smelukov could you provide a dummy example (2 htpasswd files same user + password)? + and a more complete environment (node version, sinopia version, verdaccio version, etc etc)

**Comment by ayusharma** [comment] 2018-06-20 12:04
I am closing the issue as @smelukov suggests.

**Closed by ayusharma** 2018-06-20 12:04 UTC
Labels: auth, invalid, waiting-user-feedback
