### ISSUE TITLE
Unable to publish package after changing listen address

### ISSUE THREAD

**Issue by unional** [verdaccio/verdaccio#111] opened 2017-01-18 02:05 UTC
I was trying and using `verdaccio` with the default setting (`localhost:4873`) and it was working fine.

I now change the listen address to `0.0.0.0:4873` to allow other machines accessing it.

But then I cannot publish to it anymore:

```sh
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

When I run `npm adduser` again, it complains the user already exists.

I try to uninstall and reinstall `verdaccio` but the error still presist.

How can I clear the users and start over?

EDIT: To clarify, I can't publish when I change the `package.json/publishConfig` pointing to the public ip address of the hosting machine.

Changing it back to `localhost:4873` works.

**Comment by HJoost** [comment] 2017-01-18 08:41
Same problem here :(

**Comment by Cosaquee** [comment] 2017-01-18 08:43
I do knot know why this error happens but a quick fix is to setup reverse proxy (Apache or Nginx) so you can have verdaccio running on localhost but still be accessible from other machines.

**Comment by HJoost** [comment] 2017-01-18 08:45
Please have a look at my edited comment above! (Wrong permission in the config was the failure)

**Comment by unional** [comment] 2017-01-18 09:09
I checked my config file and it doesn't have the users section. Here is my config:

```yml
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: F:/verdaccio/storage

auth:
  htpasswd:
    file: F:/verdaccio/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
listen:
  - 0.0.0.0:4873
```

**Comment by HJoost** [comment] 2017-01-18 09:15
I would try to change the listen property to something like:

- http://192.168.3.2:4873 

If this doesn't help (for test purposes only!) publish: $all

**Comment by nathanyeung** [comment] 2017-02-08 22:30
On the machine that you're trying to run verdaccio on use the local ip address:
`listen:
    - 10.0.0.5:4873`

**Comment by unional** [comment] 2017-02-08 23:30
Yes, using local address is fine.
The OP is about not able to publish with the existing user before changing from `localhost:...` to `10.x.x.x:...`.

For now, I'm using another user to publish. And will likely be my solution to my problem, because our IT will provide ArtiFactory for me in the future to publish the npm packages. This means I'll deprecate my usage of `verdaccio` soon.

However, this problem is still real and would affect other users who uses `verdaccio`.

**Comment by juanpicado** [comment] 2017-02-09 19:30
I tried and I cannot reproduce. What I did was:

1. Using a new Ubuntu installation running in a VM
2. Installed latest verdaccio (2.1.1)
3. Using your same configuration
4. I created a new user
5. I logged successfully
6. I published successfully 

````bash
Juans-MBP-2016:test jpicado$ npm adduser --registry http://172.16.10.129:4873
Username: juan
Password: 
Email: (this IS public) juan@fake.com
Logged in as juan on http://172.16.10.129:4873/.
Juans-MBP-2016:test jpicado$ npm publish --registry http://172.16.10.129:4873

> my-dummy-package@0.0.3 prepublish /Users/jpicado/projects/test
> npm run lint && npm run build


> my-dummy-package@0.0.3 lint /Users/jpicado/projects/test
> eslint .


> my-dummy-package@0.0.3 build /Users/jpicado/projects/test
> babel src/ --out-dir lib/ --copy-files

src/index.js -> lib/index.js
+ my-dummy-package@0.0.3
Juans-MBP-2016:test jpicado$ 
````
I'll need more info in order to reproduce it.

**Comment by unional** [comment] 2017-02-09 20:10
> Using a new Ubuntu installation running in a VM
> Installed latest verdaccio (2.1.1)
> First config with `http://localhost:4873`
> I created a new user
> I logged successfully
> I published successfully
> Change to `http://172.16.10.129:4873`
> Try to publish

**Comment by Aigeec** [comment] 2017-07-16 00:20
@unional are you changing the registry domain as in going from --registry=http://localhost:4873 to --registry=http://172.16.10.129:4873? 

When you add a user to npm or verdaccio it adds an entry to the users .npmrc file with the users auth token. This is domain specific. e.g.

`//localhost:4873/:_authToken="<auth token here>"` wont work for http://172.16.10.129:4873 even though its the same server. You can update your .npmrc file to the new domain.

**Comment by juanpicado** [comment] 2017-10-05 05:11
@Aigeec has the right answer to the initial question. Closing.

**Closed by juanpicado** 2017-10-05 05:11 UTC
Labels: bug, help wanted
