### ISSUE TITLE
Routing not using proxy path [windows/iis]

### ISSUE THREAD

**Issue by Steven-Harris** [verdaccio/verdaccio#1297] opened 2019-05-02 16:18 UTC
I updated from an alpha version (v4.0.0.0-alpha.2) to the latest beta and my path no longer works. I have https://domain.com/npmregistry. When I navigate to that url it shows the "Sorry, we couldn't find it" page because it's looking for a package named "npmregistry" I can click go home and the application works just fine but the url goes to https://domain.com/. Which is fine until I refresh the page or send someone a direct link.  The relative lines of my config are 
```
listen:
  - 0.0.0.0:4873
url_prefix: https://domain.com/npmregistry/
no_proxy: localhost,127.0.0.1
```
I have the registry host on a computer and proxied from a web server. The npm registry is expose through  http://<ip address>:4873 and then I have an IIS proxy on a web server to allow for access via https://domain.com/npmregistry/

**Comment by juanpicado** [comment] 2019-05-02 16:20
:-) ... I was working on it last night ... actually, I know how to fix it, soon I'll post a patch. This repo easily reproduces the bug. 

https://github.com/verdaccio/docker-examples/tree/master/reverse_proxy/nginx/relative_path

Thanks for reporting this @Steven-Harris

**Comment by juanpicado** [comment] 2019-05-02 16:40
@Steven-Harris one question, my fix will remove the `url_prefix` as you have defined there. It should not be the same something like `url_prefix: /npmregistry/` instead?

**Comment by Steven-Harris** [comment] 2019-05-02 16:43
That shouldn't be a problem - I think that's even easier for new users

**Comment by juanpicado** [comment] 2019-05-04 14:58
@Steven-Harris please try with the tag `verdaccio/verdaccio:fix-1297` and please verify the issue is being fixed in your side.

**Comment by Steven-Harris** [comment] 2019-05-06 13:55
Gave this a shot and I am getting mixed content/CORS errors. This is due to the fact I am running verdaccio http and the proxy is https. Is there anything I can do to resolve this? beta.5 didn't have this issue.

**Comment by juanpicado** [comment] 2019-05-06 18:01
@Steven-Harris could you show me what exaclty is being affected by CORS?

**Comment by Steven-Harris** [comment] 2019-05-06 18:06
This is what I am getting in the console
![image](https://user-images.githubusercontent.com/7720242/57245140-bd03d780-6fff-11e9-8bef-6369b22df387.png)

**Comment by juanpicado** [comment] 2019-05-06 18:21
Do the assets and the page have the same port? I can read different protocol in both ...

**Comment by Steven-Harris** [comment] 2019-05-06 18:24
I just have 
```
listen:
  - 0.0.0.0:4873
url_prefix: /npmregistry/
```
I am not serving my assets separate from verdaccio api

**Comment by Steven-Harris** [comment] 2019-05-06 18:27
just noticed this in a logs of verdaccio
![image](https://user-images.githubusercontent.com/7720242/57246341-ab6fff00-7002-11e9-8181-ce5c57b91e4f.png)

**Comment by juanpicado** [comment] 2019-05-06 18:40
> I just have
> 
> ```
> listen:
>   - 0.0.0.0:4873
> url_prefix: /npmregistry/
> ```
> 
> I am not serving my assets separate from verdaccio api

I meant in your reverse proxy configuration.

**Comment by Steven-Harris** [comment] 2019-05-06 18:45
oh it's just a simple iis redirect
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <outboundRules>
                <preConditions>
                    <preCondition name="ResponseIsHtml1">
                        <add input="{RESPONSE_CONTENT_TYPE}" pattern="^text/html" />
                    </preCondition>
                </preConditions>
            </outboundRules>
            <rules>
                <remove name="Redirect http to https" />
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <action type="Rewrite" url="http://remote-server:4873/{R:1}" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>

```

**Comment by juanpicado** [comment] 2019-05-06 18:54
Well, I tried with rewrite on my test with nginx and did not work at all. I'm not an expert with this so I make it simpler, this works for me pretty well. 

I think if you want to follow such approach `http://remote-server:4873/{R:1}` you will need to run https within the Docker image. 

```
server {
    listen 8080 default_server;
    access_log /var/log/nginx/verdaccio.log;
    charset utf-8;

    location / {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_set_header X-NginX-Proxy true;
      proxy_pass http://verdaccio_v4_root;
      proxy_redirect off;
    }
}
```

**Comment by Steven-Harris** [comment] 2019-05-06 18:58
Are you suggesting to have verdaccio run https? I happy to play around with it however I am not using docker in this setup just running through npm. beta.5 works perfectly fine with my current setup I am not seeing in the fix branch anything that would cause this

**Comment by juanpicado** [comment] 2019-05-07 05:42
> Are you suggesting to have verdaccio run https? 

For some reason, I thought you were using Docker.

>  I happy to play around with it however I am not using docker in this setup just running through npm. beta.5 works perfectly fine with my current setup I am not seeing in the fix branch anything that would cause this

It would be great if you run some test on your side. The `beta.5` allows set complete URL in the `url_prefix`, but with the new UI (`react-router` + `History API`) and the combination sub-directories on reverse proxies, the old approach using URL in the `url_prefix` create a lot of issues and the https://github.com/verdaccio/verdaccio/pull/1299  is changing that.

I run a lot of different test in this repo with Docker (https://github.com/verdaccio/docker-examples/tree/master/reverse_proxy/nginx).  

Unfortunately, I'm not sure whether the windows setup is still correct (https://verdaccio.org/docs/en/next/iss-server) since I don't use IIS and I have no way to test it.

**Comment by Steven-Harris** [comment] 2019-05-17 15:57
@juanpicado  I don't think this working as expected. Before the href where being transformed correctly so that they were https://domain.com/registry.  but now they are http://localhost:4873/registry. This cause mixed content errors but more over http://localhost:4873/registry doesn't exist. I believe the href should be transformed with the full url the application just needs to be configured so that it is relative to /registry

**Comment by juanpicado** [comment] 2021-03-11 10:58
I'll take of this #2122 please follow up there.

**Closed** 2021-03-24 21:31 UTC
Labels: issue: bug, topic: windows
