### ISSUE TITLE
403: error: invalid filename when pulling @scoped packages from Gemfury uplink

### ISSUE THREAD

**Issue by WesTyler** [verdaccio/verdaccio#1263] opened 2019-03-21 20:37 UTC
**Describe the bug**
When installing any `@namespace/` scoped package from a Gemfury uplink, verdaccio fails out with `403: error: invalid filename`. This appears to be due to a difference in filenames that gemfury returns for namespaced packages compared to the npm registry.

**To Reproduce**

in config.yaml
```
uplinks:
  gemfury:
    url: https://npm-proxy.fury.io/KEY/USER/
```

in .npmrc:
```
registry=http://path.to.verdaccio.proxy.com/
```

Install gemfury package with no scope through verdaccio proxy - no problems:
```
> npm install private-package1
```

Install gemfury package with scope - works only with registry set to gemfury directly. When installed through verdaccio proxy, fails with 403:
```
> npm install @private/scoped-package
npm ERR! 403 Forbidden: @private/scoped-package@^1.0.0
```

log in verdaccio server:
```
 http <-- 403, user: null(IP.REDACTED), req: 'GET /@private%2fscoped-package/-/%40private%2Fscoped-package-1.0.0', error: invalid filename
```

**Expected behavior**
Gemfury's filenames are different than the npm registry, but the npm client is able to translate them correctly when used directly. We would expect the verdaccio caching not to break this compatibility.

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: verdaccio/verdaccio:3.8.1
 - Docker Version: 18.09.0

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
```
# allow large packages to be published
max_body_size: 1000mb

# path to a directory with all packages
storage: /verdaccio/storage

# a list of other known repositories we can talk to
uplinks:
  gemfury:
    url: https://npm-proxy.fury.io/REDACTED/REDACTED/

packages:
  '**':
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: gemfury

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: -1
```

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node', '/usr/local/bin/npm', '-ddd' ]
npm info using npm@6.4.1
npm info using node@v10.15.0
```
 - `$ npm config get registry` prints:
```
https://npm-proxy.fury.io/REDACTED/REDACTED/
```
**Additional context**

**Comment by rtsao** [comment] 2019-07-02 00:00
I can confirm this is also happening for scoped packages (albeit using a different registry other than GemFury).

The most immediate explanation for this error is the regex in https://github.com/verdaccio/verdaccio/blob/acf5a791f6c685f5e471ceb59b6b2ad6338c016a/src/lib/utils.js#L68 does not allow forward slash characters (which are in the name scoped packages).

However, this is just the first failure; there are larger logic problems with scope packages it seems.

**Comment by aolvictim** [comment] 2019-07-02 21:39
I am experiencing the same issue as well when trying to install https://www.npmjs.com/package/@ember-data/-build-infra

**Comment by CalvinMcGee** [comment] 2019-07-04 09:01
I can also confirm that this is an issue

**Comment by rtsao** [comment] 2019-07-09 21:21
I put together a tentative fix for this in https://github.com/verdaccio/verdaccio/pull/1382

**Comment by juanpicado** [comment] 2019-07-11 05:37
More context about this. The filename is invalid because the filename does not end at `.tgz`.

```
"dist": {
	"shasum": "3699c74ae0e546aa540b0f0ba6e2d8ae6203a5b1",
	"tarball": "https://npm.fury.io/xxxx/~/d/%40juan%2Ftest/%40juan%2Ftest-10.0.5"
}
```
when another registry would use something like
```
"dist": {
	"shasum": "fd7b9f5d6d214b90050e8e4d7a4a9b0e6f23630d",
	"tarball": "https://registry.npmjs.org/@types%2fangular/-/angular-1.5.1-alpha.tgz"
},
```
thus the error is not much friendly, `403` might be due you did not get access to the file, but should be `500`.

```
http <-- 403, user: jpicado(127.0.0.1), req: 'GET /@juan%2ftest/-/%40juan%2Ftest-10.0.6', error: invalid filename
 info <-- 127.0.0.1 requested 'GET /@juan%2ftest'
```

In any case, the solution might be find the way to validate the name rather remove the validation (#1382) which create other issues.

**Closed** 2021-05-15 14:58 UTC
Labels: good first issue, help wanted, issue: bug
