### ISSUE TITLE
Docker Volume broken

### ISSUE THREAD

**Issue by medokin** [verdaccio/verdaccio#248] opened 2017-07-11 10:07 UTC
#### My reason:

Error: EACCES: permission denied, open '/verdaccio/conf/storage/.sinopia-db.json'

#### Steps to reproduce:

docker run -it --rm --name verdaccio -p 4873:4873 -v /compose/verdaccio/data:/verdaccio verdaccio/verdaccio

####  App Version:	

gt 2.1

####  Config file:	

default

**Comment by juanpicado** [comment] 2017-07-11 10:16
Relates https://github.com/verdaccio/verdaccio/issues/238

**Comment by medokin** [comment] 2017-07-11 10:17
2.1 seems to be the last working version.

**Comment by juanpicado** [comment] 2017-07-11 10:19
Have you tried `2.1.5`?

**Comment by medokin** [comment] 2017-07-11 10:29
I tried every version.

Well, even 2.1 does not work correctly, there is no error, but the volume is empty.

**Comment by medokin** [comment] 2017-07-11 10:41
```yaml
verdaccio:
  image: verdaccio/verdaccio:2.1 to latest
  container_name: verdaccio
  ports:
    - "4873:4873"
  volumes:
    - "/compose/verdaccio/data/storage:/verdaccio/storage"
    - "/compose/verdaccio/data/conf:/verdaccio/conf"
  restart: always
~
```

results in:

```bash
Creating verdaccio
Attaching to verdaccio
verdaccio | Verdaccio doesn't need superuser privileges. Don't run it under root.
verdaccio |  fatal--- cannot open config file /verdaccio/conf/config.yaml: ENOENT: no such file or directory, open '/verdaccio/conf/config.yaml'
verdaccio exited with code 0
```

**Comment by juanpicado** [comment] 2017-07-11 10:46
Thanks. I'll try later

**Comment by juanpicado** [comment] 2017-07-11 18:59
I'll need more data, I tested with https://github.com/verdaccio/docker-examples/tree/master/docker-local-storage-volume and I cannot reproduce it

**Comment by medokin** [comment] 2017-07-12 08:11
It does not work when I clear the conf directory. 

```
verdaccio    |  fatal--- cannot open config file /verdaccio/conf/config.yaml: ENOENT: no such file or directory, open '/verdaccio/conf/config.yaml'
```

It does not create a default config.yaml. Is this behavior wanted?

**Comment by juanpicado** [comment] 2017-07-12 13:03
Your very beginning reason is a complete different issue, please file a new issue, provide enough information and close this one if you consider the initial reason is solved already.

**Closed** 2017-07-13 10:05 UTC
Labels: docker, waiting-feedback
