### ISSUE TITLE
Wrong publish time, always 1985

### ISSUE THREAD

**Issue by moyuye** [verdaccio/verdaccio#1542] opened 2019-10-31 06:46 UTC
Environment: 
System window10.

Steps: 
1. Start the preconfigured verdaccio service first. 
2. Publish the code: 
```
npm publish --registry http://localhost:4873
```
![20191031143910](https://user-images.githubusercontent.com/13173588/67924857-a7f1b500-fbec-11e9-9b0c-c888b7f10ef9.png)
3. After the publication is successful, open the package in the verdaccio service storage directory, as shown in the figure, the time is wrong.
![20191031144132](https://user-images.githubusercontent.com/13173588/67924896-c5bf1a00-fbec-11e9-8362-1b510542f434.png)

**Hoping to fix it.**

**Comment by juanpicado** [comment] 2019-10-31 21:00
O_o .... ok ... that's odd. How this is related with Verdaccio? 🤔 That should be a job performed by Node.js. We use the standard Node.js `fs` for I/O.

**Comment by DanielRuf** [comment] 2019-11-04 06:12
Hi, this is how npm and yarn do it to prevent a bug with zip. This is only visible on the filesystem.

**Comment by DanielRuf** [comment] 2019-11-04 06:14
See https://github.com/npm/cli/search?utf8=%E2%9C%93&q=1985&type=

https://github.com/npm/cli/commit/58d2aa58d5f9c4db49f57a5f33952b3106778669

You can see the same for every package on unpkg.com.

Closing as this is not a bug on our side.

**Closed by DanielRuf** 2019-11-04 06:14 UTC
Labels: external-issue, issue: need-more-info, issue: needs triage

**Comment by DanielRuf** [comment] 2019-11-04 06:15
In general you should be able to see also the other dates (mdate, cdate, ...).

**Comment by moyuye** [comment] 2019-11-04 07:36
[https://npm.community/t/tarball-content-timestamps-locked-to-1985/149](https://npm.community/t/tarball-content-timestamps-locked-to-1985/149)

**Comment by DanielRuf** [comment] 2019-11-04 08:05
Well, imho it is a dirty hack / workaround by the npm maintainers, not a solution or the right solution ;-)
