### ISSUE TITLE
Url encoded problem

### ISSUE THREAD

**Issue by simonfr** [verdaccio/verdaccio#1777] opened 2020-04-14 16:57 UTC
**Describe the bug**
When I try to publish i get this :
```
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://domain/@scope%2fpackage - no such package available
npm ERR! 404 
npm ERR! 404  '@scope/package@0.1.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

In logs I've this :
```
 http <-- 404, user: user(*.*.*.* via *.*.*.*), req: 'PUT /@scope%2fpackage', error: no such package available
 http <-- 404, user: user(*.*.*.* via *.*.*.*), req: 'PUT /@scope%2fpackage', error: no such package available
```

**Expected behavior**
It should push correctly package

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: 4.5.1
 - Docker Version: 19.03.8
 - Traefik Version: v2.2.0

**Environment informations**
It runs behind traefik reverse proxy

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: http}
```

**Comment by dhufnagel** [comment] 2020-04-24 19:23
I ran into the same issue behind an apache reverse proxy. I fixed it by reading the docs. 
May it be, that traefik reverse proxy changes the URL?
Do you get the same problems when bypassing the proxy?

**Comment by davecaruso** [comment] 2020-05-10 04:23
if you are using an apache reverse proxy / virtual host, you need to configure it with `AllowEncodedSlashes On` and potentially `ProxyPreserveHost On`

**Comment by juanpicado** [comment] 2020-05-10 12:23
thanks for that @davecaruso

the documentation says something different https://verdaccio.org/docs/en/reverse-proxy#apache

It might be wrong, in such case would great know the difference and if your answer is the right one, update docs would be highly appreciated 👍 

https://github.com/verdaccio/website/blob/master/docs/reverse-proxy.md

**Comment by davecaruso** [comment] 2020-05-10 16:41
it does say that; and that's what i used, and it didn't work with scoped packages (not fun when you depend on babel or types and more). kept tweaking things all over the place and ... it works?

**Comment by eeve** [comment] 2020-06-01 06:48
Same problem

My problem is that there is no permission to create a folder under storage
So I started docker using root
The problem is solved, but is there any better way?

**Comment by juanpicado** [comment] 2022-11-30 22:16
Ok, seems clarified, closing.

**Closed by juanpicado** 2022-11-30 22:16 UTC
Labels: help wanted, Docker, issue_needs_triage, issue: work-around available
