### ISSUE TITLE
Authenticated access only - ends in fatal

### ISSUE THREAD

**Issue by daikiuk** [verdaccio/verdaccio#56] opened 2016-09-01 14:50 UTC
within config I allowed authenticated access only, docker container is killed at the moment request on list web interface is made or if you try to publish package while not authenticated. Used this docker image https://hub.docker.com/r/therightplace/verdaccio/

fatal --- uncaught exception, please report this
ForbiddenError: unregistered users are not allowed to access package dummy-npmv2
    at Object.allow_access (/usr/src/app/lib/auth.js:67:23)
    at next (/usr/src/app/lib/auth.js:141:7)
    at next (/usr/src/app/lib/auth.js:138:14)
    at next (/usr/src/app/lib/auth.js:138:14)
    at Auth.allow_access (/usr/src/app/lib/auth.js:146:5)
    at async.filterSeries.template.name (/usr/src/app/lib/index-web.js:52:14)
    at /usr/src/app/node_modules/async/dist/async.js:4937:13
    at replenish (/usr/src/app/node_modules/async/dist/async.js:873:21)
    at /usr/src/app/node_modules/async/dist/async.js:883:15
    at _filter (/usr/src/app/node_modules/async/dist/async.js:4936:9)

**Comment by crowebird** [comment] 2016-09-04 16:38
Yea get this too... users who are not authorized should simply not be able to see those repos, not crash the app.

**Comment by crowebird** [comment] 2016-09-04 17:08
@daikiuk - I went ahead and found the issue myself, see PR: #58

**Comment by daikiuk** [comment] 2016-09-06 10:27
@crowebird perfect, thanks.

**Comment by ben-page** [comment] 2016-09-16 20:21
duplicate of #23

**Comment by kachkaev** [comment] 2016-10-04 14:08
This is still happening to me. Any workarounds?

**Comment by nwhite89** [comment] 2016-10-06 10:57
I have the same issue with this, I would really like to move over to verdaccio from sinopia but this is preventing me.

**Comment by trentearl** [comment] 2016-10-12 00:53
This should be fixed in https://github.com/verdaccio/verdaccio/pull/58

**Comment by trentearl** [comment] 2016-10-12 00:54
and in 2.1.0

**Closed by trentearl** 2016-10-12 00:53 UTC
