### ISSUE TITLE
NPM pulls corrupted packages from Verdaccio instance (its back)

### ISSUE THREAD

**Issue by johnruck** [verdaccio/verdaccio#1349] opened 2019-06-12 18:54 UTC
Same behavior as reported in ticket #756 but those fixes dont fix the issue.  I am doing this with a fairly generic Angular 6 cli built project.  Error output from a manually issued npm install --verbose:

```
npm timing audit body Completed in 94ms
npm WARN tarball tarball data for typescript@>=2.6.2 <2.8 (sha512-p5TCYZDAO0m4G344hD+wx/LATebLWZNkkh2asWUFqSsD2OrDNhbAHuSjobrmsUmdzjJjEeZVU9g1h3O6vpstnw==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for typescript@~2.9.1 (sha512-Gr4p6nFNaoufRIY4NMdpQRNmgxVIGMs4Fcu/ujdYk3nAZqk7supzBE9idmvfZIlH/Cuj//dvi+019qEue9lV0w==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for typescript@~2.8.0 (sha512-IIU5cN1mR5J3z9jjdESJbnxikTrEz3lzAw/D0Tf45jHpBp55nY31UkUvmVHoffCfKHTqJs3fCLPDxknQTTFegQ==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @angular/compiler@6.1.10 (sha512-FPIb2j3zfoBwb6vo/u0gQeu70h8InGlSisBr3xMACs/35/pwB6kbQR+JQiUr0D7k6QApg7AuMkvq8aFNelg0aw==) seems to be corrupted. Trying one more time.
```

Note I had this behavior with Verdaccio 3, did one of the recommendations in the #756 ticket and restarted my Docker Verdaccio container which upgraded it to Verdaccio 4 (thanks for all of the help you provided in #1324 to get that working) and I now have the exact same behavior with Verdaccio 4.01.  

I have purged the node_modules and package-lock.json (and as I just rebuilt my packages tree in the new Docker instance I know those are clean).  I have done the npm cache purge commands listed in 756 and I still get the same behavior.

Odd notes - this only happens on my build server, even when it is setup to wipe the directory and clean build - on my development vm the npm install works fine, so it seems to be something related to that machine but I am not sure what it could be.  In both cases I am currently manually running the commands under my user account, so it is not like they are running under different security.  

On machine that works
npm info using npm@6.5.0
npm info using node@v10.14.2

on machine with issue
npm info using npm@6.8.0
npm info using node@v10.14.2

Any ideas/suggestions on where to look for this?  I guess I can try updating the working machine to npm 6.8 to see if it then stops working.......

Update - well, going to 6.8.0 on the working machine didnt break it, and going to 6.9.0 on the broken machine didnt fix it so I am open to suggestions on things to try.

Update 2 - well, I did a npm cache verify and then an npm update still without success, but the end of the log from the Verdaccio server is interesting:

```
 http <-- 200, user: null(172.16.121.185), req: 'GET /has-values', bytes: 0/4129
 http --> 304, req: 'GET https://registry.npmjs.org/copy-descriptor' (streaming)
 http --> 304, req: 'GET https://registry.npmjs.org/copy-descriptor', bytes: 0/0
 http <-- 200, user: null(172.16.121.185), req: 'GET /copy-descriptor', bytes: 0/2400
 http <-- 200, user: null(172.16.121.185), req: 'POST /-/npm/v1/security/audits/quick', bytes: 74646/1172
 http <-- 200, user: null(172.16.121.185), req: 'GET /typescript/-/typescript-2.7.2.tgz', bytes: 0/6076378
 http <-- 200, user: null(172.16.121.185), req: 'GET /typescript/-/typescript-2.9.2.tgz', bytes: 0/6372426
 http <-- 200, user: null(172.16.121.185), req: 'GET /typescript/-/typescript-2.8.4.tgz', bytes: 0/6034070
 http <-- 200, user: null(172.16.121.185), req: 'GET /@angular%2fcompiler/-/compiler-6.1.10.tgz', bytes: 0/5429592
 http <-- 200, user: null(172.16.121.185), req: 'GET /@angular%2fcompiler/-/compiler-6.1.10.tgz', bytes: 0/5429592
 http <-- 200, user: null(172.16.121.185), req: 'GET /typescript/-/typescript-2.9.2.tgz', bytes: 0/6372426
 http <-- 200, user: null(172.16.121.185), req: 'GET /typescript/-/typescript-2.7.2.tgz', bytes: 0/6076378
 http <-- 200, user: null(172.16.121.185), req: 'GET /performance-now/-/performance-now-2.1.0.tgz', bytes: 0/4564
 http <-- 200, user: null(172.16.121.185), req: 'GET /postcss/-/postcss-6.0.23.tgz', bytes: 0/183627
 http <-- 200, user: null(172.16.121.185), req: 'GET /uri-js/-/uri-js-3.0.2.tgz', bytes: 0/107604
 http <-- 200, user: null(172.16.121.185), req: 'GET /selenium-webdriver/-/selenium-webdriver-3.6.0.tgz', bytes: 0/776120
 http <-- 200, user: null(172.16.121.185), req: 'GET /resolve/-/resolve-1.11.0.tgz', bytes: 0/33459
 http <-- 200, user: null(172.16.121.185), req: 'GET /less/-/less-3.9.0.tgz', bytes: 0/671112
 http <-- 200, user: null(172.16.121.185), req: 'GET /typescript/-/typescript-2.8.4.tgz', bytes: 0/6034070
 http <-- 200, user: null(172.16.121.185), req: 'GET /less/-/less-3.9.0.tgz', bytes: 0/671112
```
as mentioned in the other ticket, **the problem file seem to be larger ones**.

Update 3 - I tried to disable to the caching of npmjs packages to no effect (even after doing a npm cache verify on the machine in question before redoing the npm install).  Is this the right spot to put in the cache false setting?

```
`# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: false

`
```

**Comment by juanpicado** [comment] 2019-06-12 20:35
hi @johnruck , 

>  Is this the right spot to put in the cache false setting?

`cache: false` is optional, but you **pay the penalty** to do not have tarballs cached. 

I wonder which value do you have for `max_body_size` https://verdaccio.org/docs/en/configuration#max-body-size.

⚠️  Furthermore, share the config file also helps to give us more context.

> well, going to 6.8.0 on the working machine didnt break it, and going to 6.9.0 on the broken machine didnt fix it so I am open to suggestions on things to try.

Sometimes try with either `yarn` or `pnpm` helps to spot the issue is on the client side.

> I am doing this with a fairly generic Angular 6 cli built project. Error output from a manually issued npm install --verbose:

Could you describe the steps? I'd like to try locally.

**Comment by johnruck** [comment] 2019-06-12 21:12
@juanpicado - I am willing to try the max_body_size option (where does it go in the configuration file - the web page you referenced doesnt really say or show it in context in a configuration), although if I am interpreting the output from the verdaccio properly the files seem to be within that constraint (6M in size)

For reference,. my current config.yaml was posted in #1324 earlier today, just missing the cache: false that I have since re-added that I referenced above.

I would love to be able to explain how to reproduce it, but the exact same code is working on one machine and not on another with no obvious differences between the two machines.  The machine that is failing happens to be a TeamCity agent machine, but the failures happen even when I manually invoke npm in the same directory (it is how I am debugging this issue now without involving TC).

**Comment by johnruck** [comment] 2019-06-12 21:57
pnpm output - 

```
H:\TC1-DataDirectory\ff1c88d354221106\SystemManagementServer\ClientApp>pnpm install
 WARN  deprecated @angular/http@6.1.10: Switch to @angular/common/http - see https://angular.io/guide/http
Downloading tohsaka.silverblazegaming.com+4873/@angular/compiler/6.1.10: 5.43 MB/5.43 MB, done
Downloading tohsaka.silverblazegaming.com+4873/typescript/2.8.4: 6.03 MB/6.03 MB, done
Downloading tohsaka.silverblazegaming.com+4873/typescript/2.9.2: 6.37 MB/6.37 MB, done
 WARN  @angular-devkit/build-angular: @ngtools/webpack@6.0.8 requires a peer of typescript@~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0 but version 2.8.4 was installed.m+4873/typescript/2.7.2: 6.05 MB/6.08 MB
Packages: +997
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 WARN  Fetching tohsaka.silverblazegaming.com+4873/typescript/2.7.2 failed!
 ERROR  Actual size (6052937) of tarball (http://tohsaka.silverblazegaming.com:4873/typescript/-/typescript-2.7.2.tgz) did not match the one specified in 'Content-Length' header (6076378)99 MB/6.08 MB

Seems like you have internet connection issues.
Try running the same command again.
If that doesn't help, try one of the following:

- Set a bigger value for the `fetch-retries` config.
    To check the current value of `fetch-retries`, run `pnpm get fetch-retries`.
    To set a new value, run `pnpm set fetch-retries <number>`.

- Set `network-concurrency` to 1.
    This change will slow down installation times, so it is recommended to
    delete the config once the internet connection is good again: `pnpm config delete network-concurrency`

NOTE: You may also override configs via flags.
For instance, `pnpm install --fetch-retries 5 --network-concurrency 1`
Resolving: total 999, reused 0, downloaded 996
Downloading tohsaka.silverblazegaming.com+4873/typescript/2.7.2: 5.99 MB/6.08 MB
Error: Actual size (6052937) of tarball (http://tohsaka.silverblazegaming.com:4873/typescript/-/typescript-2.7.2.tgz) did not match the one specified in 'Content-Length' header (6076378)
    at WriteStream.opts.stream.on (C:\Users\john\AppData\Roaming\npm\node_modules\pnpm\lib\node_modules\@pnpm\tarball-fetcher\lib\createDownloader.js:162:29)
    at WriteStream.emit (events.js:182:13)
    at lazyFs.close (internal/fs/streams.js:208:14)
    at C:\Users\john\AppData\Roaming\npm\node_modules\pnpm\lib\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
Error: Actual size (6052937) of tarball (http://tohsaka.silverblazegaming.com:4873/typescript/-/typescript-2.7.2.tgz) did not match the one specified in 'Content-Length' header (6076378)
    at WriteStream.opts.stream.on (C:\Users\john\AppData\Roaming\npm\node_modules\pnpm\lib\node_modules\@pnpm\tarball-fetcher\lib\createDownloader.js:162:29)
    at WriteStream.emit (events.js:182:13)
    at lazyFs.close (internal/fs/streams.js:208:14)
    at C:\Users\john\AppData\Roaming\npm\node_modules\pnpm\lib\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
Error: Actual size (6052937) of tarball (http://tohsaka.silverblazegaming.com:4873/typescript/-/typescript-2.7.2.tgz) did not match the one specified in 'Content-Length' header (6076378)
    at WriteStream.opts.stream.on (C:\Users\john\AppData\Roaming\npm\node_modules\pnpm\lib\node_modules\@pnpm\tarball-fetcher\lib\createDownloader.js:162:29)
    at WriteStream.emit (events.js:182:13)
    at lazyFs.close (internal/fs/streams.js:208:14)
    at C:\Users\john\AppData\Roaming\npm\node_modules\pnpm\lib\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
Error: Actual size (6052937) of tarball (http://tohsaka.silverblazegaming.com:4873/typescript/-/typescript-2.7.2.tgz) did not match the one specified in 'Content-Length' header (6076378)
    at WriteStream.opts.stream.on (C:\Users\john\AppData\Roaming\npm\node_modules\pnpm\lib\node_modules\@pnpm\tarball-fetcher\lib\createDownloader.js:162:29)
    at WriteStream.emit (events.js:182:13)
    at lazyFs.close (internal/fs/streams.js:208:14)
    at C:\Users\john\AppData\Roaming\npm\node_modules\pnpm\lib\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)

```

Make any sense to you?

**Comment by johnruck** [comment] 2019-06-13 18:13
ok, I managed to do some more testing in a separate new directory and I was able to get it to work with the cache turned off with both pnpm and npm.  I then turned on caching to see if it would break again (and I got the 4.02 docker image) - it broke again once I re-enabled the caching.

**Comment by DanielRuf** [comment] 2019-06-14 07:02
Canyou check the size of the actual tarball on disk? Maybe it is an issue with some compression or additional metadata in it.

**Comment by johnruck** [comment] 2019-06-17 20:50
Sorry for taking this long to respond, I am not entirely sure how to interpret these results - in looking at the file in the docker storage zone (for typescript 2.9.2.tgz)

```
john@tohsaka:~$ docker run -it --rm -v verdaccio-storage:/verdaccio/storage -v /home/john/verdaccio/storage:/backup ubuntu bash -c "ls -al /verdaccio/storage/typescript/typescript-2.9.2.tgz"
-rw-r--r-- 1 10001 65533 6372426 Jun 12 18:22 /verdaccio/storage/typescript/typescript-2.9.2.tgz
john@tohsaka:~$ docker run -it --rm -v verdaccio-storage:/verdaccio/storage -v /home/john/verdaccio/storage:/backup ubuntu bash -c "sha512sum /verdaccio/storage/typescript/typescript-2.9.2.tgz"
1abe29ea714d6a8b9f44863834c76941136683154818cb3815cbbfba37589379c066a93bb2ea73044f62766bdf648947fc2ba3fff76f8bed35f6a12e7bd955d3  /verdaccio/storage/typescript/typescript-2.9.2.tgz
```

while on the machine where it is failing to download - 
`npm WARN tarball tarball data for typescript@~2.9.1 (sha512-Gr4p6nFNaoufRIY4NMdpQRNmgxVIGMs4Fcu/ujdYk3nAZqk7supzBE9idmvfZIlH/Cuj//dvi+019qEue9lV0w==) seems to be corrupted. Trying one more time.
`

I am not sure if those two checksums should match (ie - whether the npm checksum reported should be for the whole file or a segment of it) 

The file size does match what verdaccio is reporting the filesize to be (if am reading the diagnostics right):

```
 http <-- 200, user: null(172.16.121.185), req: 'GET /typescript/-/typescript-2.7.2.tgz', bytes: 0/6076378
 http <-- 200, user: null(172.16.121.185), req: 'GET /typescript/-/typescript-2.9.2.tgz', bytes: 0/6372426
 http <-- 200, user: null(172.16.121.185), req: 'POST /-/npm/v1/security/audits/quick', bytes: 70063/820
 http <-- 200, user: null(172.16.121.185), req: 'GET /typescript/-/typescript-2.9.2.tgz', bytes: 0/6372426
 http <-- 200, user: null(172.16.121.185), req: 'GET /typescript/-/typescript-2.7.2.tgz', bytes: 0/6076378

```

Were you wanting me to check the tarball size on the npm side? If so can you tell me where it is getting stored as when I look in %appdata%/npm-cache-typescript all I see is the 2.4.2 version.

**Comment by johnruck** [comment] 2019-06-17 21:04
Here is a piece of useful info - I have managed to isolate down the package.json to a point where I can trigger the failure:
```

{
  "name": "SystemManagementServer",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:ssr": "ng run SystemManagementServer:server:dev",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "6.1.10",
    "@angular/compiler": "6.1.10",
    "@angular/core": "6.1.10"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.0",
    "@angular/cli": "~6.0.0",
    "@angular/compiler-cli": "6.1.10",
    "typescript": "~2.8.0"
  },
  "optionalDependencies": {}
}

```
As the file is configured above, I can consistently get it to say the typescript 2.9.2 is corrupt.  If I remove the @angular-devkit/build-angular line, then typescript 2.9.2 is not flagged as being corrupt.  I dont know enough about npm to try to figure out from this what is happening, but maybe this file might be able to trigger it for you as well.  I was testing by just putting this file in a new subdirectory and running npm install off of it.

**Comment by johnruck** [comment] 2019-06-17 21:08
btw - today's replies from me were against the Verdaccio 4.0.3 docker image updated today.

**Comment by johnruck** [comment] 2019-06-17 21:11
Err dang, I just realized, my package.json was pulling 2.8* so the package I removed was the one pulling the 2.9.* in, let me see if it flags it as corrupt if I bump it to 2.9.*

**Comment by johnruck** [comment] 2019-06-17 21:22
hmm, ok, I think I have stumbled upon the cause/effect, but I need an explanation because npm is not behaving as I thought it did.  If I switch the typescript my original package.json file was referencing from ~2.8.0 to ~2.9.0 npm no longer reports corrupted packages.  

My understanding was that any packages referenced by other packages were installed in the node_modules directory under the referencing package (so that version mismatches between referenced tools would not interact with each other), so I am at a loss for explaining how a mismatch between a top level referenced package and a dependency of a another package could interfere with each other.  Can one of you explain this to me?

**Comment by johnruck** [comment] 2019-06-18 22:49
Ok, I am still at this (switching my teamcity build agent to run under user account instead of system to see if I can get it working that way - good news is Verdaccio now reports my user account, bad news is still corrupted packages).  Right now I have a question on interpreting the diagnostics that come out of Verdaccio.  In these lines it says "Streaming"

```
 http --> 304, req: 'GET https://registry.npmjs.org/es5-ext' (streaming)
 http --> 304, req: 'GET https://registry.npmjs.org/es5-ext', bytes: 0/0
 http --> 304, req: 'GET https://registry.npmjs.org/typescript' (streaming)
 http --> 304, req: 'GET https://registry.npmjs.org/typescript', bytes: 0/0
 http --> 304, req: 'GET https://registry.npmjs.org/@angular%2Fcore' (streaming)
 http --> 304, req: 'GET https://registry.npmjs.org/@angular%2Fcore', bytes: 0/0

```

Does this indicate where Verdaccio is actually pulling a new file as opposed to just returning a file from its cache?  I am just trying to see some indicator of where it redownloads the file from the npmjs.org servers.

**Comment by johnruck** [comment] 2019-06-18 23:44
Well, I have manually pulled the typescript-2.9.2.tgz on another machine (via straight http) and its sha512sum matches the one in the Verdaccio storage volume, so where does npm pull down its files these days when it repulls and fails them so that I can see what is different in the file it is getting.

**Comment by johnruck** [comment] 2019-06-19 16:10
If I pull the typescript-2.9.2.tgz via browser on the machine in question from the Verdaccio server, it also seems to match the SHA512 I am getting from the other machines, so this appears to be some sort of npm interaction issue or something with how npm is getting the data feed.

**Comment by johnruck** [comment] 2019-06-19 17:29
On a whim I tried to limit npm to just one download at a time (using --maxsockets=1, it didnt seem to resolve the problem but I was able to see the downloads happening much slower so I think the option did work from that standpoint.  It might be important that I see npm complain about the 2.9 and 2.7 typescripts, but it always redownloads those two and the 2.8 one as well, like they are somehow stepping on each other.
```

```
 http <-- 200, user: null(172.16.121.185), req: 'POST /-/npm/v1/security/audits/quick', bytes: 61732/818
 http <-- 200, user: jruck(172.16.121.185), req: 'GET /typescript/-/typescript-2.9.2.tgz', bytes: 0/6372426
 http <-- 200, user: jruck(172.16.121.185), req: 'GET /typescript/-/typescript-2.7.2.tgz', bytes: 0/6076378
 http <-- 200, user: jruck(172.16.121.185), req: 'GET /typescript/-/typescript-2.8.4.tgz', bytes: 0/6034070

```

Here is the teamcity build log output, I wonder if the .staging\typescript-#### are all stepping on each other......

```
Checkout directory: H:\TC1-DataDirectory\c617351503b7bc54
[12:13:47]Step 1/1: test (Command Line) (3m:25s)
[12:13:52][Step 1/1] Starting: C:\TeamcityTC1\temp\agentTmp\custom_script8243164111786357582.cmd
[12:13:52][Step 1/1] in directory: H:\TC1-DataDirectory\c617351503b7bc54
[12:13:52][Step 1/1]         1 file(s) copied.
[12:13:52][Step 1/1] C:\Program Files\nodejs\\node.exe
[12:13:52][Step 1/1] C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js
[12:13:53][Step 1/1] C:\Users\tcba\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
[12:13:53][Step 1/1] 6.9.0
[12:13:53][Step 1/1] C:\Program Files\nodejs\\node.exe
[12:13:53][Step 1/1] C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js
[12:13:55][Step 1/1] C:\Users\tcba\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
[12:14:07][Step 1/1] npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
[12:14:07][Step 1/1] npm WARN deprecated   npm i nyc
[12:14:07][Step 1/1] npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
[12:16:32][Step 1/1] npm WARN tarball tarball data for typescript@~2.9.1 (sha512-Gr4p6nFNaoufRIY4NMdpQRNmgxVIGMs4Fcu/ujdYk3nAZqk7supzBE9idmvfZIlH/Cuj//dvi+019qEue9lV0w==) seems to be corrupted. Trying one more time.
[12:16:55][Step 1/1] npm WARN tarball tarball data for typescript@>=2.6.2 <2.8 (sha512-p5TCYZDAO0m4G344hD+wx/LATebLWZNkkh2asWUFqSsD2OrDNhbAHuSjobrmsUmdzjJjEeZVU9g1h3O6vpstnw==) seems to be corrupted. Trying one more time.
[12:17:12][Step 1/1] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\chokidar\node_modules\fsevents):
[12:17:12][Step 1/1] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[12:17:12][Step 1/1] npm WARN @angular/core@6.1.10 requires a peer of zone.js@~0.8.26 but none is installed. You must install peer dependencies yourself.
[12:17:12][Step 1/1] npm WARN @ngtools/webpack@6.0.8 requires a peer of typescript@~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0 but none is installed. You must install peer dependencies yourself.
[12:17:12][Step 1/1] npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
[12:17:12][Step 1/1] 
[12:17:12][Step 1/1] npm ERR! path H:\TC1-DataDirectory\c617351503b7bc54\node_modules\.staging\typescript-1171c6e3\lib\tsserverlibrary.js
[12:17:12][Step 1/1] npm ERR! code EPERM
[12:17:12][Step 1/1] npm ERR! errno -4048
[12:17:12][Step 1/1] npm ERR! syscall unlink
[12:17:13][Step 1/1] npm ERR! Error: EPERM: operation not permitted, unlink 'H:\TC1-DataDirectory\c617351503b7bc54\node_modules\.staging\typescript-1171c6e3\lib\tsserverlibrary.js'
[12:17:13][Step 1/1] npm ERR!  { [Error: EPERM: operation not permitted, unlink 'H:\TC1-DataDirectory\c617351503b7bc54\node_modules\.staging\typescript-1171c6e3\lib\tsserverlibrary.js']
[12:17:13][Step 1/1] npm ERR!   cause:
[12:17:13][Step 1/1] npm ERR!    { Error: EPERM: operation not permitted, unlink 'H:\TC1-DataDirectory\c617351503b7bc54\node_modules\.staging\typescript-1171c6e3\lib\tsserverlibrary.js'
[12:17:13][Step 1/1] npm ERR!      errno: -4048,
[12:17:13][Step 1/1] npm ERR!      code: 'EPERM',
[12:17:13][Step 1/1] npm ERR!      syscall: 'unlink',
[12:17:13][Step 1/1] npm ERR!      path:
[12:17:13][Step 1/1] npm ERR!       'H:\\TC1-DataDirectory\\c617351503b7bc54\\node_modules\\.staging\\typescript-1171c6e3\\lib\\tsserverlibrary.js' },
[12:17:13][Step 1/1] npm ERR!   stack:
[12:17:13][Step 1/1] npm ERR!    'Error: EPERM: operation not permitted, unlink \'H:\\TC1-DataDirectory\\c617351503b7bc54\\node_modules\\.staging\\typescript-1171c6e3\\lib\\tsserverlibrary.js\'',
[12:17:13][Step 1/1] npm ERR!   errno: -4048,
[12:17:13][Step 1/1] npm ERR!   code: 'EPERM',
[12:17:13][Step 1/1] npm ERR!   syscall: 'unlink',
[12:17:13][Step 1/1] npm ERR!   path:
[12:17:13][Step 1/1] npm ERR!    'H:\\TC1-DataDirectory\\c617351503b7bc54\\node_modules\\.staging\\typescript-1171c6e3\\lib\\tsserverlibrary.js',
[12:17:13][Step 1/1] npm ERR!   parent: '@angular-devkit/build-optimizer' }
[12:17:13][Step 1/1] npm ERR! 
[12:17:13][Step 1/1] npm ERR! The operation was rejected by your operating system.
[12:17:13][Step 1/1] npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
[12:17:13][Step 1/1] npm ERR! or that you lack permissions to access it.
[12:17:13][Step 1/1] npm ERR! 
[12:17:13][Step 1/1] npm ERR! If you believe this might be a permissions issue, please double-check the
[12:17:13][Step 1/1] npm ERR! permissions of the file and its containing directories, or try running
[12:17:13][Step 1/1] npm ERR! the command again as root/Administrator (though this is not recommended).
[12:17:13][Step 1/1] 
[12:17:13][Step 1/1] npm ERR! A complete log of this run can be found in:
[12:17:13][Step 1/1] npm ERR!     C:\Users\tcba\AppData\Roaming\npm-cache\_logs\2019-06-19T17_17_12_773Z-debug.log
[12:17:13][Step 1/1] Process exited with code -4048
[12:17:13][Step 1/1] Process exited with code -4048 (Step: test (Command Line))
[12:17:13][Step 1/1] Step test (Command Line) failed

```

the teamcity build step being referenced (command line runner):

```
copy h:\test3\package.json
call npm -v
call npm install --maxsockets=1

```
and that package.json

```
{
  "name": "SystemManagementServer",
  "version": "0.0.0",
  "scripts": {},
  "private": true,
  "dependencies": {
    "@angular/common": "6.1.10",
    "@angular/compiler": "6.1.10",
    "@angular/core": "6.1.10"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.0",
    "@angular/cli": "~6.0.0",
    "@angular/compiler-cli": "6.1.10",
    "typescript": "~2.8.0"
  },
  "optionalDependencies": {}
}

```

**Comment by johnruck** [comment] 2019-06-19 17:50
One other datapoint, I went and deleted the node_modules and package-lock.json files, after this (when doing it myself from a command prompt and not using teamcity) for the first run I got the corrupted files message but a re-run had no corrupted files.  I notice that the corrupted file messages are saying the checksum for a different version of the package - typescript@~2.9.1 when the actual package returned was 2.9.2, so is this maybe a problem where the checksums are being reported for the wrong file which is why they fail and why redownloading the file doesnt resolve the issue?

I dont know where to look to see what checksums are being returned each time.

**Comment by toddwong** [comment] 2019-06-23 06:25
Set server.keepAliveTimeout in config to a large value works for me (or with the new version 4.0.4, set it to zero also works)

**Comment by mrivera7** [comment] 2020-05-19 12:04
I'm having the same issue with other packages when I try to use create-react-app to initialize a new react project using the default react template. I'm not exactly sure how to approach a fix on this.

**Comment by mrivera7** [comment] 2020-05-22 03:48
Upgrading from Ubuntu 18 LTS to Ubuntu 20 LTS seems to have fixed the issue for me.

**Comment by juanpicado** [comment] 2020-05-22 07:57
If you have issues downloading larger files, then https://github.com/verdaccio/verdaccio/pull/1207 fix the issue.  

Add a custom value in the `config.yaml` file. A reminder this is supported Node 8 an higher,
````
server:
  keepAliveTimeout: 60
```

https://verdaccio.org/docs/en/configuration#server

I'm closing this one, feel free to share more feedback.

**Closed** 2020-05-22 07:57 UTC
Labels: issue: needs triage
